### ISSUE TITLE
Feature Request: Playlist Editor to hide imported groups and channels

### ISSUE THREAD

**Issue by jimmymarbles** [SenexCrenshaw/StreamMaster#109]
I would like the playlist editor to have the ability to hide groups from view in the playlist and not show associated streams in the stream list.  Currently, visibility that is set will turn the groups and streams red, but are still seen and also included in the auto renumbering.  I would like the ability that all would be visually hidden and hopefully not included in the auto renumbering.

**Comment by SenexCrenshaw** [comment]
just turn of visibility these is a box for that
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/35600301/5bad7fc4-a203-4b4d-89e0-1b8faf2d703f)

all of the tables have this.
