### ISSUE TITLE
Feature Request: M3U & XMLTV URL information

### ISSUE THREAD

**Issue by jimmymarbles** [SenexCrenshaw/StreamMaster#11]
It would be very helpful if the M3U &XMLTV URL information posted on a header within SM.

Thanks!

**Comment by SenexCrenshaw** [comment]
They are here: WIki needs updating

<img width="449" alt="image" src="https://github.com/SenexCrenshaw/StreamMaster/assets/35600301/8c74784c-b21a-46cf-976f-9cab5af4d845">
