### ISSUE TITLE
Bug: Using a DDNS instead of local IP to access SM causes NS Binding errors and infinite self-refreshing of the website

### ISSUE THREAD

**Issue by R0ltec** [SenexCrenshaw/StreamMaster#127]
**Describe the Bug**
Last few builds have caused an issue that when visiting SM from a DDNS URL, it causes NS Binding Errors which all appear to be blocked by SM and it causes the site to refresh at a rate of about twice per second, indefinitely.

**Stream Master Info**
- Version Number - just went to -44 build and it still exists.

**Link to logs (required)**
Let me know which logs you would need. Cause again, if I F12 in Firefox and check the box that says 'Disable Cache", the website refreshes one last time but loads correctly.

**Comment by dp247** [comment]
I think this might be limited to Firefox - this happens when I try it in Firefox, but not in Opera GX.

**Comment by SenexCrenshaw** [comment]
I'm pushing a redirect patch today. Some broswer/os combos seem to  have an issue with a permanent redirect. Hopefully this addresses it

**Comment by R0ltec** [comment]
Running 0.2.18-45 I no longer have this issue with Firefox with "Disable cache" now disabled. Thank you.
