### ISSUE TITLE
Feature Request: Change the category name within the M3U link to the stream group name

### ISSUE THREAD

**Issue by R0ltec** [SenexCrenshaw/StreamMaster#128]
Every m3u link for the stream groups created contain all channels within the same named "All" Group-Title. This is a big problem when exporting to a service like IptvEditor or importing the m3u's into TiviMate which is what everyone I setup is using. Everything then wants to import into the same All category(group-title) defeating a major purpose of the m3u links SM is able to provide.

Can this please be changed so that the category/group-title matches the same name given under Stream Groups?

**Comment by SenexCrenshaw** [comment]
the m3u output set the group to whatever you set it to be. I am not sure what you mean. can you show me an example?

**Comment by R0ltec** [comment]
You can close this out. Maybe its a random thing or maybe it was already resolved. At least for now I can no longer duplicate it. But to provide more reference:
Example. I named a stream group within SM to "Backup Playlist" and then I downloaded the m3u file. If I edited that m3u file, it would tell me that the Group-Title wasn't "Backup Playlist" but instead, "All". This would be absolutely horrible when exporting multiple playlists and all arriving at the client with the same group name, or category name, whichever everyone wants to go by.
