### ISSUE TITLE
Feature: Stream Testing

### ISSUE THREAD

**Issue by Austin1** [SenexCrenshaw/StreamMaster#130]
I have no idea why some channels work better than others, but sometimes a channel I pick will be garbage and I have to go try another and switch it out in SM. If there was a way to see the channel performance before selecting it, that would be great.

E.g., could you hit a test button a popup the stream in the browser to see how it performs or even build an algorithm to check the quality of the stream before it's selected?

**Comment by SenexCrenshaw** [comment]
i eventually will collect stream health and statistics but that is down the line. to test it live would be a disaster for folks with limited stream access.
