### ISSUE TITLE
Bug: custom epg info is not showing in the webui/m3u file

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#134]
**Describe the Bug**
not able to see custom epg data in the web ui preventing me from testing https://github.com/SenexCrenshaw/StreamMaster/issues/102 to see if it has been fixed

**Stream Master Info**
vite-0.2.18-vite.1-0052

**Link to logs (required)**
can provide if needed. in the meanwhile here are some screenshots comparison between an old working build and this one.
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/a4dcc493-f2e2-4d3e-8bbd-aab6f523e23d)
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/30434df6-4278-4213-972e-15fec6b0d9c4)

**Comment by lavazza2017** [comment]
yes, I have same problem if I have 2 EPG lists

**Comment by aniel300** [comment]
> yes, I have same problem if I have 2 EPG lists

am not sung epg at all. this info was manually entered by me in the "tvg-id"

**Comment by aniel300** [comment]
fixed as per "senexcrenshaw/streammaster:stream-fixer-upper-0.3.2-stream-fixer-upper.1-0067"...clsoing
