### ISSUE TITLE
Ability to add and autorefresh local EPG files

### ISSUE THREAD

**Issue by jaragoncr99** [SenexCrenshaw/StreamMaster#145]
**Is your feature request related to a problem? Please describe.**
Most IPTV guides suck. I use Guide2Go (Alturismo container) to pull the EPG and create the files that i need. In Xteve I mounted it to a local file and Xteve treated it like a URL 

**Describe the solution you'd like**
Treat a local file/XML like a URL for EPGs

**Describe alternatives you've considered**
I would need a webserver on another container, but I'm trying to keep it simple.

**Comment by jaragoncr99** [comment]
This is superseded by the work to add SD directly.

**Comment by Dleewee** [comment]
I see issue closed as superseded by Schedules Direct integration. But for anyone wanting to update from a local file, I believe this is possible -
Depending on your file paths, simply update the local file under: ~/.streammaster/PlayLists/EPG/$filename.xmltv
Same for M3U: ~/.streammaster/PlayLists/M3U/$filename.m3u
Should be possible to use a simple CRON job to automate downloading updated files and saving to the correct folder.
