### ISSUE TITLE
Bug: Warning 

### ISSUE THREAD

**Issue by lavazza2017** [SenexCrenshaw/StreamMaster#146]
**Describe the Bug**
Every time when I added EPG list it shows in logs:
Couldn't find handler for /discover.json
Couldn't find handler for /lineup_status.json

Can you explain what is that ?

**Stream Master Info**
- Version Number 0.3.0

**Link to logs (required)**
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/29400771/e386cb1e-41ac-4b29-ac23-042d3a05b5a1)

**Comment by SenexCrenshaw** [comment]
seems like a config issue. check your docker-compose
