### ISSUE TITLE
Bug: clicking on a group auto selects it. is this working as design? 

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#15]
**Describe the Bug**
when in the "playlist" section, clicking on a group will auto select it, is this working as design, if yes, can u add an option to change this behavior? 
**Stream Master Info**
- latest docker tag/ custom version we are working with. 

**Link to logs (required)**
(https://gist.github.com/aniel300/435df62ea02056a9e6b759df960022ce)

**Comment by SenexCrenshaw** [comment]
it was originally by design when it the checkboxes weren't there. I changed the behavior to not select.

I was thinking of making it that it would select the row if nothing else is selected.

**Comment by aniel300** [comment]
> No worries. Im pushing a new image with this change (10 mins)

thanks
