### ISSUE TITLE
Feature Request: HLS proxying insights and configuration

### ISSUE THREAD

**Issue by bruor** [SenexCrenshaw/StreamMaster#150]
I'm currently using [HLS-proxy](https://www.hls-proxy.com/) with Emby, but doing testing with streammaster. 

The buffer setup in streammaster seems to mimic xteve's settings and is based on the size of the buffer in MB.  If possible, I would like to get more insight into HLS streams that are being proxied in the status area,  as well as controls around the startup of HLS streams, retry values etc.  Changing the buffer settings to use chunks vs size makes the buffer work uniformly for streams that use different HLS chunk sizes.  

Here is how data is represented in HLS-proxy to give you some context
The bars in the from window represents the file chunks that have been downloaded
The gray box represents what the client has last requested from the server, the green bars are buffered files that haven't been requested by the client yet. 

![image](https://github.com/SenexCrenshaw/StreamMaster/assets/454516/29ea89b3-28dc-41f7-a8fb-d27f2cb307ef)

There are also settings to control fast playback of the stream, so you can feed the client only X files to start, and then increase the number that you allow it to grab after which allows the stream to start more quickly and keeps clients like emby from skipping to the most recent chunk and experiencing issues with buffering. 

![image](https://github.com/SenexCrenshaw/StreamMaster/assets/454516/6e9fe68a-1535-47d1-94d5-1fd39ca316c8)

**Comment by SenexCrenshaw** [comment]
SM just moves bits around right now. it doesnt care about the data or has any insight into it.
