### ISSUE TITLE
Bug: CPU utilization by 'dotnet StreamMasterAPI.dll' seems high when streaming

### ISSUE THREAD

**Issue by jbf154** [SenexCrenshaw/StreamMaster#151]
**Describe the Bug**
- When streaming a channel, the CPU usage of SM seems higher than expected when using FFmpeg:
![high CPU usage](https://github.com/SenexCrenshaw/StreamMaster/assets/16122392/4d443d90-2bb0-48ed-a51f-101df7f124a7)

**Stream Master Info**
- Version Number: 0.3.0.0

**Link to logs (required)**
- Upload any relevant logs here [Gist](http://gist.github.com). NA

**Comment by SenexCrenshaw** [comment]
not an SM bug.
