### ISSUE TITLE
Bug: Issue saving settings

### ISSUE THREAD

**Issue by obnoxiousish** [SenexCrenshaw/StreamMaster#152]
Hello, the save settings is done over a websocket, some settings like User-Agent save fine BUT ffmpeg command line arguments does not save

The reason for this is because, when the websocket sends the packet to save the settings it supplies the default ffmpeg command as "ffmpegDefaultCommand" : -hide_banner -loglevel error -i {streamUrl} -c copy -f mpegts pipe:1

i want to add -c:a libmp3lame to transcode the audio

and i cant please fix this asap

**Comment by obnoxiousish** [comment]
I believe this same error is happening with the authentication settings, I cant set a username and password etc

**Comment by obnoxiousish** [comment]
Update: use sudo docker exec -t -i streammaster /bin/bash to enter your docker container and visit /config/ and edit settings.json and these things can be manually edited.

Sad this is the best option, other option is bugfixing yourself and making a PR or making your own build

**Comment by SenexCrenshaw** [comment]
> Update: use sudo docker exec -t -i streammaster /bin/bash to enter your docker container and visit /config/ and edit settings.json and these things can be manually edited.
> 
> Sad this is the best option, other option is bugfixing yourself and making a PR or making your own build

if you have to exec into the container to edit /config... then your docker-compose is wrong. /config should be mapped to a local directory on your host.

**Comment by TrashyMcTrashMan** [comment]
i have the same exact problem, and I followed the "installation guide". Most people copy pasta what's in the guide, so nothing is changed from what the dev provided.

**Comment by SenexCrenshaw** [comment]
check your docker-compose
https://github.com/SenexCrenshaw/StreamMaster/wiki/Installation#docker-compose
