### ISSUE TITLE
Bug: building default image url improperly

### ISSUE THREAD

**Issue by obnoxiousish** [SenexCrenshaw/StreamMaster#153]
# Setting.cs

```
 public string DefaultIcon { get; set; } = "images/default.png";
```

this needs to be /images/default.png i believe, as of right now when it builds a EPG file itll make URLs like "https://master.obnoxious.lolimages/default.png"

note the missing / between l and i 

It seems the lead dev on this project doesnt read open issues despite actively maintaining the project so i might make a pull request (but it might get ignored) or idk

**Comment by obnoxiousish** [comment]
Note: Seems the backend may have support for changing this string but the frontend does not, (guessing, the websocket for saving settings sends it over.)

**Comment by SenexCrenshaw** [comment]
Check with the latest and reopen if need be.
