### ISSUE TITLE
Bug: Backup/additional streams don't work as expected

### ISSUE THREAD

**Issue by jbf154** [SenexCrenshaw/StreamMaster#154]
**Describe the Bug**
I have 2 IPTV URLs for the same channel, say `url1` and `url2`. If I edit `url1` to have `url2` as an "additional stream," tune to the `url1` channel, and inspect the SM logs, I only ever see it try `url2` and not `url1`. I would assume it would try `url1` first, then `url2`. I believe this is due to the [`EnsureChannelRegistration` method's implementation](https://github.com/SenexCrenshaw/StreamMaster/blob/main/StreamMasterInfrastructure/VideoStreamManager/Channels/ChannelManager.cs#L276).

**Stream Master Info**
- Version Number: 0.3.0.0

**Link to logs (required)**
- *N/A*

**Comment by SenexCrenshaw** [comment]
check latest. the main url, if provided, will be use as the first stream.
