### ISSUE TITLE
Feature Request: Delete Imported M3U Group names when M3U file is removed.

### ISSUE THREAD

**Issue by jimmymarbles** [SenexCrenshaw/StreamMaster#16]
I removed my imported M3U file, but when I remove it, the imported stream groups are still listed.  Would it be possible to have a delete option or have them deleted upon removal of the M3U file?

![image](https://github.com/SenexCrenshaw/StreamMaster/assets/6432197/4ef11c08-abd7-45c4-8d0e-ff3959da2957)

**Comment by aniel300** [comment]
am also experiencing this as well on my end

**Comment by SenexCrenshaw** [comment]
You can have multiple streams from different files in the same group though. 

How about if the file is deleted and the group has no streams assigned, then I delete the group?
