### ISSUE TITLE
Bug: can't rename custom made output/ m3u groups

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#167]
**Describe the Bug**
can't rename custom made groups, ui reflect it but after a f5 old name comes back. not sure if restarting the container would make a difference

**Stream Master Info**
- latest

**Link to logs (required)**
- can provide if needed

**Comment by Jakyrian** [comment]
Not an issue anymore in the 0.16.0.0+ releases, closing.
