### ISSUE TITLE
Bug: Logos are not always displayed correctly and uneditable

### ISSUE THREAD

**Issue by johnhelt** [SenexCrenshaw/StreamMaster#176]
**Describe the Bug**
When editing the channel (edit video stream), some streams do not show the logo, instead an URL is shown. When manually selecting the logo from the logo dropdown, after searching for the channel name, the channel cannot be updated (greyed out + icon):

![videostream1](https://github.com/SenexCrenshaw/StreamMaster/assets/43775572/a6c978ea-3215-4433-ba74-bcb83aac29c5)

**Stream Master Info**
- 0.3.2.0

**Link to logs (required)**
- No relevant log messages can be seen

**Comment by SenexCrenshaw** [comment]
Check latest

**Comment by SenexCrenshaw** [comment]
Check with the latest and reopen if need be.
