### ISSUE TITLE
Feature Request: can u add a "select all option here"

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#180]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
can u add a "select all option here" and/or a way to edit the default "all" group to be able to select or not select certains groups.

**Describe alternatives you've considered**
n/a

**Additional context**
![chrome_wwaPl3MEtF](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/ec1e0d79-8e34-4622-b3dd-0c99127277b2)

**Comment by SenexCrenshaw** [comment]
not with the current setup.

**Comment by aniel300** [comment]
ok
