### ISSUE TITLE
Feature Request: Relational Databases (mariadb, mysql, postgresql etc.)

### ISSUE THREAD

**Issue by korncola** [SenexCrenshaw/StreamMaster#181]
sqlite is not very reliable (today mine broke again)
The option to use a decent relational database like mysql, mariadb or postgresql would be awesome.
Also the database could than be on a seperated host.
I am no .NET dev but with a database model and adapter it shouldnt be too much work to implement persistance database vendor agnostic.

Thank you, great software :)

**Comment by SenexCrenshaw** [comment]
sqlite is very stable. check your configuration settings for issues. So many application use this. radarr/sonarr/..... Submit a PR if you want a diff ORM.
