### ISSUE TITLE
Bug: Custom channel numbering was lost

### ISSUE THREAD

**Issue by jbf154** [SenexCrenshaw/StreamMaster#188]
**Describe the Bug**
I did a bunch of custom numbering for the streams in my m3u. After a few days, it was all lost.

**Stream Master Info**
- Version Number: senexcrenshaw/streammaster:0.3.2-0012

**Link to logs (required)**
- Logs show an M3U refresh. Afterwards, tuning any channel from Plex fails because the numbers changed.

**Comment by Jakyrian** [comment]
Closing issue as stale, should have been fixed at some point. Try running the latest container.
