### ISSUE TITLE
Bug: Problem with any EPG

### ISSUE THREAD

**Issue by lavazza2017** [SenexCrenshaw/StreamMaster#189]
**Describe the Bug**
I have tried 6 of latest version and to be honest I never find the way to add streams to Plex. Why ... because of EPG... I can't download or see "epg.xml" 

I made/make 6 steps:
1. Added M3U File (it is big 80 000+ streams but after 3-4 min it added successfully) 
2. Added EPG File (https://epg.ovh/pl.xml with polish streams + icons)
3. Added one new STREAM GROUP and then select polish streams (200 streams via group)
4. After hmm 1-3h epg attached to streams 
5. Copy link HDHR to PLEX it sees all streams fine
6. copy link to epg and here is fail (tried download, see, in programs, browser etc)

I have tried to turn off Cache Icons same problem, Always use EPG Logo same problem close to all settings I'm end with same problem.

Most of time (2 versions) logs are without any warning errors etc. 
Sometimes but not always I got this (log in "link to logs")

Streams and EPG working fine on xTeVe so I'm very curious why it doesn't work here any hit or ideas ?

**Stream Master Info**
- Version Number
Latest on 10.12.2023

**Link to logs (required)**

Information | 12/10/2023, 08:52:32 PM | GetPagedStreamGroupVideoStreamsHandler.Handle executed in 30 ms.
-- | -- | --
Error | 12/10/2023, 09:10:33 PM | An unhandled exception has occurred while executing the request.
Error | 12/10/2023, 09:10:33 PM | AutoMapper.AutoMapperMappingException: Error mapping types. Mapping types: List`1 -> List`1 System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> System.Collections.Generic.List`1[[StreamMasterDomain.Dto.ProgrammeNameDto, StreamMasterDomain, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]] ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping. Mapping types: String -> ProgrammeNameDto System.String -> StreamMasterDomain.Dto.ProgrammeNameDto at lambda_method1805(Closure, String, ProgrammeNameDto, ResolutionContext) at lambda_method1804(Closure, Object, List`1, ResolutionContext) --- End of inner exception stack trace --- at lambda_method1804(Closure, Object, List`1, ResolutionContext) at StreamMasterApplication.Programmes.Queries.GetPagedProgrammeNameSelectionsHandler.Handle(GetPagedProgrammeNameSelections request, CancellationToken cancellationToken) in /src/StreamMasterApplication/Programmes/Queries/GetPagedProgrammeNameSelections.cs:line 49 at StreamMasterApplication.Common.Behaviours.PerformanceBehaviour`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /src/StreamMasterApplication/Common/Behaviours/PerformanceBehaviour.cs:line 37 at StreamMasterAPI.Controllers.ProgrammesController.GetPagedProgrammeNameSelections(ProgrammeParameters Parameters) in /src/StreamMasterAPI/Controllers/ProgrammesController.cs:line 34 at lambda_method1768(Closure, Object) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited\|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at StreamMasterInfrastructure.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in /src/StreamMasterInfrastructure/Middleware/CacheHeaderMiddleware.cs:line 23 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited\|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
Error | 12/10/2023, 09:10:33 PM | An unhandled exception has occurred while executing the request.
Error | 12/10/2023, 09:10:33 PM | AutoMapper.AutoMapperMappingException: Error mapping types. Mapping types: List`1 -> List`1 System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> System.Collections.Generic.List`1[[StreamMasterDomain.Dto.ProgrammeNameDto, StreamMasterDomain, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]] ---> AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping. Mapping types: String -> ProgrammeNameDto System.String -> StreamMasterDomain.Dto.ProgrammeNameDto at lambda_method1805(Closure, String, ProgrammeNameDto, ResolutionContext) at lambda_method1804(Closure, Object, List`1, ResolutionContext) --- End of inner exception stack trace --- at lambda_method1804(Closure, Object, List`1, ResolutionContext) at StreamMasterApplication.Programmes.Queries.GetPagedProgrammeNameSelectionsHandler.Handle(GetPagedProgrammeNameSelections request, CancellationToken cancellationToken) in /src/StreamMasterApplication/Programmes/Queries/GetPagedProgrammeNameSelections.cs:line 49 at StreamMasterApplication.Common.Behaviours.PerformanceBehaviour`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) in /src/StreamMasterApplication/Common/Behaviours/PerformanceBehaviour.cs:line 37 at StreamMasterAPI.Controllers.ProgrammesController.GetPagedProgrammeNameSelections(ProgrammeParameters Parameters) in /src/StreamMasterAPI/Controllers/ProgrammesController.cs:line 34 at lambda_method1768(Closure, Object) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited\|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at StreamMasterInfrastructure.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in /src/StreamMasterInfrastructure/Middleware/CacheHeaderMiddleware.cs:line 23 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited\|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
Information | 12/10/2023, 09:10:44 PM | GetStreamGroupEPGHandler.PrepareEpgData executed in 1125273 ms.

**Comment by lavazza2017** [comment]
Small update... 
epg-love-0.3.2-epg-love.1-0054 this version is a bit better ... I can download xml but now I can't assign epg to stream which mean xml is empty ...

**Comment by lavazza2017** [comment]
epg-love-0.3.2-epg-love.1-0067 it's start working ... however again problem with images from EPG (to many request), any auto assign epg=streams ?

**Comment by SenexCrenshaw** [comment]
Check with the latest and reopen if need be.
