### ISSUE TITLE
Bug:  Hidden channels reappear after m3u update

### ISSUE THREAD

**Issue by paralyser** [SenexCrenshaw/StreamMaster#192]
**Describe the Bug**
Channels set to hidden reappear after refreshing the m3u playlist. However hiding a the whole group works fine.

**Stream Master Info**
- Version Number: 0.4.1.0 and tried also in 0.3.2.2

**Link to logs (required)**
- Does not generate error in LOGS. Btw, logging is disabled in my version ツ

**Comment by Jakyrian** [comment]
Assuming this is fixed, closing.
