### ISSUE TITLE
Drag n' Drop streams within the stream group page to re-order

### ISSUE THREAD

**Issue by doc-jay** [SenexCrenshaw/StreamMaster#193]
Within the stream group page, after streams have been selected and added.  It would be a nice feature if users could click and drag on a stream and move it up or down within the list, let go as to where they want it to be within the list.  It could auto number the channel positively or negatively as to how it was already numbered within the list.  

It beneficial as some guides (for clients) sort the guide based on the channel number.

**Comment by Austin1** [comment]
+1
