### ISSUE TITLE
Bug: Contaiiner won't move forward if Sched Direct SD-JSON service is down and Sched direct is used as EPG.

### ISSUE THREAD

**Issue by doc-jay** [SenexCrenshaw/StreamMaster#197]
**Describe the Bug**
If the Sched Direct SD-JSON service goes down, the container will not start successfully.  Using the cached EPG file in the 'cache' folder could be used as a fallback until the Sched Direct service is back online.  A log entry about not being able to contact Sched direct could also act as a clue about the state of the service if it goes offline.

**Stream Master Info**
- 0.4.1-93

**Link to logs (required)**
- Upload any relevant logs here [Gist](http://gist.github.com). _Do not upload attachments_.

**Comment by SenexCrenshaw** [comment]
fixed in latest
