### ISSUE TITLE
Bug: Import xmltv doesnt show up 

### ISSUE THREAD

**Issue by shaike1** [SenexCrenshaw/StreamMaster#203]
**Describe the Bug**
import xmltv.gz from provider loaded but not shown

**Stream Master Info**
- Version Number

**Link to logs (required)**
- Upload any relevant logs here [Gist](http://gist.github.com). _Do not upload attachments_.

**Comment by x1ao4** [comment]
Same here.

**Comment by ardoviniandrea** [comment]
Same here
I am on docker 0.8.1 and I cannot add any EPG/XML file.
The UI seems to load correctly until the point of displaying "Uploaded EPG", but actually never save or store it.

**Comment by litio2001** [comment]
I have the same problem, I have tried with different XML/GZ format guides (compressed) according to the docker log:

`Exception EPG From Form System.FormatException: String '2024040830000 +0000' was not recognized as a valid DateTime.`

**Comment by DieguitoCigala** [comment]
> I have the same problem, I have tried with different XML/GZ format guides (compressed) according to the docker log:
> 
> `Exception EPG From Form System.FormatException: String '2024040830000 +0000' was not recognized as a valid DateTime.`
> 
> The version in docker is 0.14.4.0

I have the same problem

System.FormatException: The DateTime represented by the string '20240824240000 +0200' is not supported in calendar 'System.Globalization.GregorianCalendar'.

I'm using version 0.14.6

**Comment by Crosus97** [comment]
i have the same proble that @DieguitoCigala

**Comment by SenexCrenshaw** [comment]
fixed in latest

**Comment by SenexCrenshaw** [comment]
follow here
#264 
fixed in latest
