### ISSUE TITLE
Bug: EPG file is empty when using DUMMY

### ISSUE THREAD

**Issue by ardoviniandrea** [SenexCrenshaw/StreamMaster#208]
**Describe the Bug**
SM 0.10.1.0, I have completed the mapping of my playlist with my EPG, but when I go to the "stream group" tab both EPG links (secure and unsecure), return an empty epg file.
M3U links works perfectly as intended

<img width="2056" alt="Screenshot 2024-02-09 at 15 00 48" src="https://github.com/SenexCrenshaw/StreamMaster/assets/15173161/57a73e05-702a-4789-af4e-c1f2610c7861">

**Stream Master Info**
- 0.10.1.0 (docker)

**Link to logs (required)**
- Log tab (and file) are also empty in this version

**Comment by ardoviniandrea** [comment]
Updated to 0.13.1.0 and the issue still persists.

I checked more and try a few different things.
When I create a new stream group and add very few streams (<20), the EPG gets generated correctly, but as soon as I add more it gets back to an empty file (a 6 bytes file containing only "<tv />" in the first line)

**Comment by ardoviniandrea** [comment]
Did additional testing
The issue is when you have any DUMMY EPG set, the file fails to generate and default to an empty one.
<img width="677" alt="Screenshot 2024-02-14 at 14 43 33" src="https://github.com/SenexCrenshaw/StreamMaster/assets/15173161/812c3582-7571-4003-af5b-121d606e4cc7">

**Comment by Jakyrian** [comment]
Closing as issue is stale, please update to 0.16.0.0+ and re-open a new issue if necessary.
