### ISSUE TITLE
streammaster v0.14.0 PostgreSQL not ready

### ISSUE THREAD

**Issue by Till1012** [SenexCrenshaw/StreamMaster#215]
Hello,
the new version (v0.14.0) won't launch on a fresh docker-compose install.
Previous versions launched just fine.
I'm using the docker-compose file from the wiki.

Output of docker-compose:

[+] Running 2/1
 ✔ Network streammaster_default  Created                                                  0.1s 
 ✔ Container streammaster        Created                                                  0.0s 
Attaching to streammaster
streammaster  | Allowing use of questionable username.
streammaster  | Adding user `nonRootUser' ...
streammaster  | Adding new group `nonRootUser' (1000) ...
streammaster  | Adding new user `nonRootUser' (1000) with group `nonRootUser (1000)' ...
streammaster  | Creating home directory `/home/nonRootUser' ...
streammaster  | Copying files from `/etc/skel' ...
streammaster  | Adding new user `nonRootUser' to supplemental / extra groups `users' ...
streammaster  | Adding user `nonRootUser' to group `users' ...
streammaster  | Changing ownership of /app to 1000:1000
streammaster  | Changing ownership of /config to 1000:1000
streammaster  | Configuration:
streammaster  | --------------
streammaster  | PGADMIN:
streammaster  |   Platform Type: debian
streammaster  |   Setup Email: admin@sm.com
streammaster  |   Setup Password: ********
streammaster  | POSTGRES:
streammaster  |   User: sm
streammaster  |   Password: ********
streammaster  |   DB Name: StreamMaster
streammaster  |   Data Directory: /config/DB
streammaster  |   Set Perms: 1
streammaster  | OS:
streammaster  |   User: postgres Group: postgres
streammaster  |   UID: 100 GID: 102
streammaster  | No backup files found in /config/Restore.
streammaster  | No files ready for restoration.
streammaster  | The files belonging to this database system will be owned by user "postgres".
streammaster  | This user must also own the server process.
streammaster  | 
streammaster  | The database cluster will be initialized with locale "C".
streammaster  | The default database encoding has accordingly been set to "SQL_ASCII".
streammaster  | The default text search configuration will be set to "english".
streammaster  | 
streammaster  | Data page checksums are disabled.
streammaster  | 
streammaster  | initdb: error: directory "/config/DB" exists but is not empty
streammaster  | initdb: hint: If you want to create a new database system, either remove or empty the directory "/config/DB" or run initdb with an argument other than "/config/DB".
streammaster  | Attempt 1: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
streammaster  | Attempt 2: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
streammaster  | Attempt 3: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
streammaster  | Attempt 4: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
streammaster  | Attempt 5: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
streammaster  | Attempt 6: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
streammaster  | Attempt 7: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
streammaster  | Attempt 8: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds

**Comment by brunomgalmeida** [comment]
Its because of the directory Backup inside. Why not use the postgres docker image instead, and remove all the manual db configuration? And/or support sqlite?

**Comment by infosecmatters2021** [comment]
It looks to me that the PUID (1000) and PGID (1000) aren't respected. Postgres is the owner of the database and must also own the server process. Postgres is PUID=100 and PGID=102. 

Not necessarily the best answer (but works) - update the PUID and PGID to match postgres. The streammaster directory (volume) also requires the same ownership/group.

Log excerpt:
streammaster | Changing ownership of /app to 1000:1000
streammaster | Changing ownership of /config to 1000:1000
...
streammaster | User: postgres Group: postgres
streammaster | UID: 100 GID: 102
…
streammaster | The files belonging to this database system will be owned by user "postgres".
streammaster | This user must also own the server process.

Changes:
environment:
      - PUID=100 # UID to Run As
      - PGID=102 # GID to Run As

volumes:
      - ~/.streammaster:/config

~/.streammaster needs its permissions set to 100 (chown) and 102 (chgrp).

**Comment by infosecmatters2021** [comment]
Pulled the latest code that includes the update to this issue. Set PUID and PGID in Docker compose. Set directory permissions (streammaster and all sub-folders) to same user/group. Started streammaster. It appears to be the same issue. (Once launched, the DB directory permissions are set to 100/102.)

Changing ownership of /app to 1026:100
Changing ownership of /config to 1026:100
...
OS:
  User: 1026 Group: 100
  User: postgres Group: postgres
  UID: 100 GID: 102
No backup files found in /config/Restore.
No files ready for restoration.
Attempt 1: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
mkdir: cannot create directory '/config': Permission denied

**Comment by macinsight** [comment]
Yup, experiencing the same on 0.14.4, this is a fatal bug on systems where you're unable to get UID 100 (e.g. shared seedboxes where you don't have root) and causes SM to be stuck in "Attempt 2: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds..." which repeats ad infinitum

**Comment by capps1994** [comment]
if this had a separate postgres container, you could also so the `depends_on` attribute meaning that the streammaster container will not start until postgres is up

**Comment by w-marco** [comment]
With 0.14.5 (which is available on Dockerhub), you can use external PSQLs:

https://github.com/SenexCrenshaw/StreamMaster/issues/217#issuecomment-2080621813

**Comment by akuaman** [comment]
i have the same problem lastest docker image.

Attempt 2: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...

**Comment by Jakyrian** [comment]
See the latest docker-compose file [here](https://senexcrenshaw.github.io/StreamMaster/GettingStarted/), should solve any postgres issues.

**Comment by akuaman** [comment]
Sorry, the problem persist in the lastest docker image

**Comment by Jakyrian** [comment]
Can you elaborate and/or attach logs

**Comment by akuaman** [comment]
Changing ownership of /app to 1000:1000
Changing ownership of /config to 1000:1000
Configuration:
--------------
PGADMIN:
  Platform Type: debian
  Setup Email: admin@sm.com
  Setup Password: ********

:
  User: postgres
  Password: ********
  DB Name: StreamMaster
  Host: 127.0.0.1
  Is DB Local: 1
  Data Directory: /config/DB
  Set Perms: 1
OS:
  User: 1000 Group: 1000
  User: postgres Group: postgres
  UID: 100 GID: 102
No backup files found in /config/Restore.
No files ready for restoration.
Attempt 1: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 2: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...

**Comment by Jakyrian** [comment]
Can you also share your docker-compose.yml file please

**Comment by akuaman** [comment]
services:
  streammaster:
    image: senexcrenshaw/streammaster:latest
    container_name: streammaster
    ports:
      - 7095:7095
      - 7096:7096
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_USER=postgres # Default
      - POSTGRES_PASSWORD=sm123 # Default
      - PGDATA=/config/DB # Default
      - POSTGRES_HOST=127.0.0.1 # Default
      - POSTGRES_DB=StreamMaster # Default
      - BACKUP_VERSIONS_TO_KEEP=5 # Default
    restart: unless-stopped
    volumes:
      - /data/streammaster:/config
      - /data/streammaster/tv-logos:/config/tv-logos

**Comment by Jakyrian** [comment]
Can you try:

`streammaster:
    image: senexcrenshaw/streammaster:latest
    container_name: streammaster
    ports:
      - 7095:7095
      - 7096:7096
    environment:
      - PUID=1000
      - PGID=1000
      - POSTGRES_USER=sm
    restart: unless-stopped
    volumes:
      - /data/streammaster:/config
      - /data/streammaster/tv-logos:/config/tv-logos`
      
That's what I have in my docker-compose file at the moment, and I wonder if the new "default" credentials are clashing with what they used to be set to.

**Comment by akuaman** [comment]
The same
Changing ownership of /app to 1000:1000
Changing ownership of /config to 1000:1000
Configuration:
--------------
PGADMIN:
  Platform Type: debian
  Setup Email: admin@sm.com
  Setup Password: ********

:
  User: sm
  Password: ********
  DB Name: StreamMaster
  Host: 127.0.0.1
  Is DB Local: 1
  Data Directory: /config/DB
  Set Perms: 1
OS:
  User: 1000 Group: 1000
  User: postgres Group: postgres
  UID: 100 GID: 102
No backup files found in /config/Restore.
No files ready for restoration.
Attempt 1: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 2: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 3: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 4: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 5: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 6: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 7: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 8: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 9: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 10: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 11: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 12: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 13: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 14: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 15: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 16: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 17: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 18: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 19: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 20: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Error: PostgreSQL on 127.0.0.1:5432 is not ready after 20 attempts.
Error: PostgreSQL is not ready.
Changing ownership of /app to 1000:1000
Changing ownership of /config to 1000:1000
Configuration:
--------------
PGADMIN:
  Platform Type: debian
  Setup Email: admin@sm.com
  Setup Password: ********

:
  User: sm
  Password: ********
  DB Name: StreamMaster
  Host: 127.0.0.1
  Is DB Local: 1
  Data Directory: /config/DB
  Set Perms: 1
OS:
  User: 1000 Group: 1000
  User: postgres Group: postgres
  UID: 100 GID: 102
No backup files found in /config/Restore.
No files ready for restoration.
Attempt 1: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 2: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 3: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...

**Comment by Jakyrian** [comment]
Hmmm frustrating. Is this a new database or one you’ve populated before?

If new then I’d suggest deleting the config volume and starting from scratch, to see if the issue gets solved that way.

**Comment by akuaman** [comment]
i delete the data and still continue the error

**Comment by akuaman** [comment]
0777

**Comment by akuaman** [comment]
root@80bda8e3f106:/app# ls -l /config/
total 24
drwxr-xr-x 2 nonRootUser nonRootUser 4096 Nov  5 11:49 Cache
drwx------ 2 postgres    postgres    4096 Nov  5 11:49 DB
drwxr-xr-x 2 nonRootUser nonRootUser 4096 Nov  5 11:49 HLS
drwxr-xr-x 2 nonRootUser nonRootUser 4096 Nov  5 11:49 Logs
drwxr-xr-x 4 nonRootUser nonRootUser 4096 Nov  5 11:49 PlayLists
drwxr-xr-x 2 nonRootUser nonRootUser 4096 Nov  5 11:49 tv-logos
root@80bda8e3f106:/app#

**Comment by akuaman** [comment]
the same, the other day work, i try in other machine and works well.

**Comment by akuaman** [comment]
inside de DB path no files

**Comment by akuaman** [comment]
Proxmox LXC debian container

root@dmznew:~# uname -v
#1 SMP PREEMPT_DYNAMIC PMX 6.8.12-2 (2024-09-05T10:03Z)

**Comment by akuaman** [comment]
This?

root@dmznew:/data/streammaster# ls -lsa
total 32
4 drwxrwxrwx  8 root    root     4096 Nov  5 08:56 .
4 drwxr-xr-x 19 root    root     4096 Nov  5 11:49 ..
4 drwxrwxrwx  2    1000     1000 4096 Nov  5 08:56 Cache
4 drwx------  2 postfix ssl-cert 4096 Nov  5 08:56 DB
4 drwxrwxrwx  2    1000     1000 4096 Nov  5 08:56 HLS
4 drwxrwxrwx  2    1000     1000 4096 Nov  5 08:56 Logs
4 drwxrwxrwx  4    1000     1000 4096 Nov  5 08:56 PlayLists
4 drwxrwxrwx  2    1000     1000 4096 Nov  5 08:56 tv-logos

**Comment by akuaman** [comment]
the same error

root@dmznew:/data/streammaster# chown -R 1000:1000 /data/streammaster

Changing ownership of /app to 1000:1000
Changing ownership of /config to 1000:1000
Configuration:
--------------
PGADMIN:
  Platform Type: debian
  Setup Email: admin@sm.com
  Setup Password: ********

:
  User: postgres
  Password: ********
  DB Name: StreamMaster
  Host: 127.0.0.1
  Is DB Local: 1
  Data Directory: /config/DB
  Set Perms: 1
OS:
  User: 1000 Group: 1000
  User: postgres Group: postgres
  UID: 100 GID: 102
Restore path does not exist: /config/Restore
No files ready for restoration.
Attempt 1: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 2: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 3: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 4: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 5: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 6: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 7: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 8: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 9: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...
Attempt 10: PostgreSQL is not yet ready on 127.0.0.1:5432. Retrying in 5 seconds...

**Comment by akuaman** [comment]
you have this log:

chmod: changing permissions of '/config/DB': Operation not permitted

but not mine

**Comment by SenexCrenshaw** [comment]
delete everything in your local config dir and make sure you use the latest

**Comment by akuaman** [comment]
Sorry the same error.
