### ISSUE TITLE
Feature Request: external PostgreSQL

### ISSUE THREAD

**Issue by korncola** [SenexCrenshaw/StreamMaster#217]
Happy to see you diteched SQLite for PostgreSQL, I proposed this some month ago :)
Would be happy if we could pass an external PostgreSQL host via the compose.

Thank you, and big Kudos to the dev pace you have recently, just wow!
Kind regards

**Comment by w-marco** [comment]
With 0.14.5 this basically already works (at least from what I can tell).

Create a User in your external postgres with the rights to create new Databases. Then use these env-vars:

```
POSTGRES_USER={USER_HERE}
POSTGRES_PASSWORD={PASSWORD_HERE}
POSTGRES_HOST={HOST_HERE}
POSTGRES_DB=iptvproxy
```

For me this just works with a Postgres 13 in a seperate docker container.

**Comment by Jakyrian** [comment]
See the full docker-compose config [here](https://senexcrenshaw.github.io/StreamMaster/GettingStarted/) for all the PostgreSQL variables:
`      - POSTGRES_USER=postgres # Default
      - POSTGRES_PASSWORD=sm123 # Default
      - PGDATA=/config/DB # Default
      - POSTGRES_HOST=127.0.0.1 # Default
      - POSTGRES_DB=StreamMaster # Default`
