### ISSUE TITLE
Bug: FATAL:  role "root" does not exist

### ISSUE THREAD

**Issue by Crosus97** [SenexCrenshaw/StreamMaster#218]
**Describe the Bug**
 - I just create with the wiki[ guide](https://github.com/SenexCrenshaw/StreamMaster/wiki/Installation)
 - i use this docker compose: [link](https://github.com/SenexCrenshaw/StreamMaster/wiki/Installation#docker-compose)

      
      Because the [docker_compose.yml](https://github.com/SenexCrenshaw/StreamMaster/blob/main/docker-compose.yml) i think is outdated:
      
      I try to join in the web and is connection refused:
      
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/46854222/90a96e1c-8d92-4d80-9180-8480c3a7e522)
     
    

**Stream Master Info**
- lastest (i dont know how to find it, but i create today with lastest)

**Link to logs (required)**
- (https://gist.github.com/Crosus97/f39b09f2df557e6ca4bfc8da14ab6c91)

**Comment by Linusten** [comment]
same issue here, any workarounds??
