### ISSUE TITLE
Bug: Stuck streams on certain clients – streams can`t be killed

### ISSUE THREAD

**Issue by jwproduction** [SenexCrenshaw/StreamMaster#219]
I primarily use streammaster with emby. That works wonderfully. I would also like to use other clients, especially UHF (https://www.uhfapp.com/) as a client for iOS and tvOS. 

Unfortunately, when using the client, the streams are often not removed when they are no longer being watched.  The problem seems to occur with various other clients (apps)

**Current result:**
Streams are getting stucked on certain clients (apps). They can`t be killed manually. Only a restart of the container solves the problem. 

**Expected result:**
Streams shoud get killed if they are no longer in use
It should be possible to kill a stream 

**Comments:** 

- It should be reproducible via the iOS app from UHF ((https://www.uhfapp.com/)) and other similar apps. 

- I will try to add some logs in the next days.

**Stream Master Info**
- Version Number: 0.14.2.0

**Link to logs (required)**
- will be added in the next days

**Comment by SenexCrenshaw** [comment]
check the latest. Should be resolved.

**Comment by jwproduction** [comment]
@SenexCrenshaw Great. Succesfully tested. Now it works :-)
