### ISSUE TITLE
Feature Request: EPG Name in EPG Search when setting EPG in playlist Editor

### ISSUE THREAD

**Issue by iceman73** [SenexCrenshaw/StreamMaster#22]
**Is your feature request related to a problem? Please describe.**
I have Multiple EPGs for the Same Channel, as sometimes the USA All EPG is not correct, so i will change the channel EPG to a locally mapped EPG. The issue is it seems both EPGs have the Channel named the same way. This leads to confusion on which EPG source I am selecting to map the Channel to.

**Describe the solution you'd like**
Since we assign a name to each EPG, could you append the name of the EPG next to the channel EPG name when searching to assign an EPG entry to a channel.
Another Alternative might be the option to select a specific EPG before searching for the channel so you know exactly what EPG source you are selecting from

**Describe alternatives you've considered**
NONE other exist at this time,

**Additional context**

**Comment by SenexCrenshaw** [comment]
This has been addressed in the latest build
