### ISSUE TITLE
Bug: Stream blocks other requests 

### ISSUE THREAD

**Issue by cascooscuro** [SenexCrenshaw/StreamMaster#224]
**Describe the Bug**
A stream that initiates a connection to the provider and it's slow to respond will block requests to other streams.
In this case the streams are from different providers and I have configured a high number of simultaneous connections.

The issue happens with "Streammaster" buffer. 

Steps to reproduce:
1. Open "Slow" stream (URL1 in logs)
2. Open another stream (URL2). The stream will not start until the first stream errors

If I change to "ffmpeg" it works ok: the moment I close the "slow" stream and start another request it will start immediately.

**Stream Master Info**
0.14.4.0 configured with "Streammaster" buffer

**Link to logs (required)**
https://gist.github.com/cascooscuro/d38b2d8d3c53a7f11d71f643d069262b

Thanks!!

**Comment by Jakyrian** [comment]
I believe this was fixed in the latest release, update and make sure you're running 0.15.0.60+ (this will require you to start from scratch as the database is not compatible with the 0.14 release).

A similar case was extensively tested and resolved (during the 0.15 beta).

**Comment by SenexCrenshaw** [comment]
fixed in latest
