### ISSUE TITLE
Bug: SchedulesDirect not fetching new schedule data

### ISSUE THREAD

**Issue by daryl249** [SenexCrenshaw/StreamMaster#225]
**Describe the Bug**
SD data does not appear to be getting fetched unless the container is restarted.  On two seperate occasions I have run out of SD guide data after 7 days of uptime while xmltv sources are still showing 7+ days of data.  A simple restart grabs new SD data.

**Stream Master Info**
0.14.4

**Link to logs (required)**
Restarted 17 hours ago:
https://gist.github.com/daryl249/967802f9b4856d8edb3b0d105c86a21b

**Comment by jaybird2203** [comment]
Can add that I noticed this as well. My setup is only SD for epg data and the queue only listed the EPG related items at the time of startup.

**Comment by Jakyrian** [comment]
Going to assume this is fixed in the latest releases (0.16.3.0+), but please re-open if it's still an issue.
