### ISSUE TITLE
Kodi EPG compatibiliy issue with IPTVSimpleClient (buildin official addon)

### ISSUE THREAD

**Issue by Estarna** [SenexCrenshaw/StreamMaster#226]
When correctly configured in iptvsimple client addon in Kodi
Channels are loading and playing as expected

EPG not showing.

however when converting with tool like https://xmlgrid.net/ it says that file is good and save to another format.

EPG now showing in Kodi

Stream Master 0.14.4.0

Kodi log says: 2024-04-03 15:48:20.437 T:9240    error <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::Epg::LoadEPG - Unable parse EPG XML: Error parsing start element tag, offset: 0:

**Comment by Estarna** [comment]
Adding :

<?xml version="1.0" encoding="UTF-8" ?>

on the first line seems to make it compliant. I just added this line on top of one D/L from the SM server and... it works!
I know that some players are looking for this tag. Why, I don't know.

https://www.tutorialspoint.com/xml/xml_encoding.htm

**Comment by Estarna** [comment]
As a temporary fix, this command line inserts the tag on the first line on the XML file generated by SM

sed -i '1i <?xml version="1.0" encoding="UTF-8" ?>' /Some_Share_Directory/Some_EPG_File.xml

Kodi can now read the EPG XML file in IPTV Simple Client

**Comment by CnC-ode** [comment]
hello

am I missing something, or could you not set this flag to false?

https://github.com/SenexCrenshaw/StreamMaster/blob/5a2704bd52d6449ba418c50a8e5e5711ba2cc1d3/EPGFormatter/Program.cs#L81

**Comment by SenexCrenshaw** [comment]
Good catch, thats the line. Its been added to the new PR
#216

**Comment by DieguitoCigala** [comment]
When is the new version going to be released with the latest pull request?
