### ISSUE TITLE
Bug: role "postgres" does not exist

### ISSUE THREAD

**Issue by kpirnie** [SenexCrenshaw/StreamMaster#230]
Unhandled exception. Npgsql.PostgresException (0x80004005): 28000: role "postgres" does not exist

**Stream Master Info**
- 0.14.6

Using Compose
```services:
  streammaster:
    image: senexcrenshaw/streammaster:latest
    container_name: pirnie_streammaster
    hostname: pirnie_streammaster
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - 7095:7095
      - 5432:5432
    volumes:
      - /home/kpirnie/pirnie-media/streammaster:/config
      - /home/kpirnie/pirnie-media/streammaster/tv-logos:/config/tv-logos
      - /home/kpirnie/pirnie-media/iptv-lists:/playlists
    devices:
      - /dev/dri:/dev/dri
    tmpfs: /tmp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8G```

**Comment by simoncaron** [comment]
Default user of the embedded pg database was changed from [sm in 0.14.4](https://github.com/SenexCrenshaw/StreamMaster/blob/1d7733d92426897c55390371d4514f81edae3301/env.sh#L4C1-L4C20) to [postgres in 0.14.6.](https://github.com/SenexCrenshaw/StreamMaster/blob/da58829dc44609f11cfc8e1d1847fe538d8083e9/env.sh#L4)

If you add the env var **POSTGRES_USER** and set it to **sm**, your install will start properly.

**Comment by Jakyrian** [comment]
Closing as resolved, the latest docker-compose file can be found here: https://senexcrenshaw.github.io/StreamMaster/nb/GettingStarted/
