### ISSUE TITLE
Bug: Multiple channels with same EPG source does result in faulty EPG result

### ISSUE THREAD

**Issue by panderssanders** [SenexCrenshaw/StreamMaster#232]
**Describe the Bug**
When adding the same TV channel twice (from differnt sources) to a streaming group and assigning the same EPG source to both channels, the resulting EPG contains only the correct data for the second/last added channel. 

**Schema** 

Stream Group

     +-----------------+       +-----------------+
     |    Channel A 1  |------>|      EPG 1      |
     +-----------------+       +-----------------+

     +-----------------+       +-----------------+
     |    Channel A 2  |------>|      EPG 1      |
     +-----------------+       +-----------------+

              | Resulting EPG
              V
     +------------------------------------------+
     |       Resulting EPG                      |
     | (only contains EPG data for Channel A 2) |
     +------------------------------------------+

**Stream Master Info**
- Version Number 0.14.6.0

**Comment by SenexCrenshaw** [comment]
fixed in latest
