### ISSUE TITLE
Bug: "Set Time Shift" does not work for channels

### ISSUE THREAD

**Issue by bradmurray** [SenexCrenshaw/StreamMaster#234]
**Describe the Bug**
The set time shift feature on the playlists page does not save. If I click the set time shift button for a channel and set the time shift to 3, save it and then refresh it resets to zero. With dev tools open I see that no network requests are even made to the back-end. I see the events below in the log, but that is it.

**Stream Master Info**
0.14.6.0

**Link to logs (required)**
info: UpdateChannelGroupCountRequestHandler.Handle[0]
      UpdateChannelGroupCountRequestHandler.Handle executed in 1 ms.
info: UpdateChannelGroupCountRequestHandler.Handle[0]
      UpdateChannelGroupCountRequestHandler.Handle executed in 1 ms.
info: GetStreamGroupsFromChannelGroupQueryHandler.Handle[0]
      GetStreamGroupsFromChannelGroupQueryHandler.Handle executed in 1 ms.
info: UpdateChannelGroupCountRequestHandler.Handle[0]
      UpdateChannelGroupCountRequestHandler.Handle executed in 1 ms.
info: UpdateVideoStreamRequestHandler.Handle[0]
      UpdateVideoStreamRequestHandler.Handle executed in 16 ms.

**Comment by SenexCrenshaw** [comment]
fixed in latest
