### ISSUE TITLE
username & password secure m3u and epg links

### ISSUE THREAD

**Issue by hossihub** [SenexCrenshaw/StreamMaster#238]
Thanx for a great product!

I would like to submit a feature request to make it possible to assign a password or username & password for each stream group via the ui interface that can be passed via the link to each.

?username=XXX&password=XXX

**Comment by SenexCrenshaw** [comment]
the new pr will have this. it will be a SG key which creates the encrypted urls. Change that and all the old urls are invalidated. change the serverkey and all urls will be invalidated.

**Comment by SarkarKurdish** [comment]
> the new pr will have this. it will be a SG key which creates the encrypted urls. Change that and all the old urls are invalidated. change the serverkey and all urls will be invalidated.

Any date or estimate when this PR will be available?

**Comment by Jakyrian** [comment]
It's available now, if you update the container you should see that you're running 0.15.0.60+ (this will require you to start from scratch as the database is not compatible with the 0.14 release)
