### ISSUE TITLE
Bug: missing header in EPG xml

### ISSUE THREAD

**Issue by t2pierre** [SenexCrenshaw/StreamMaster#245]
**Describe the Bug**
EPG xml are not parsed by Kodi's IPTV simple add-on because « <?xml version="1.0" encoding="UTF-8" ?> » is missing on top of the generated EPG xml file.

**Stream Master Info**
0.14.6

**Link to logs (required)**
logs in KODI/IPTV : error <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - Unable parse EPG XML: Start-end tags mismatch, offset: 0:

**Comment by SenexCrenshaw** [comment]
try latest
