### ISSUE TITLE
Bug: Additional Stream / Backup Channel did not work

### ISSUE THREAD

**Issue by Lip90** [SenexCrenshaw/StreamMaster#246]
I have stored different backup channels for one channel. These are not loaded. As soon as a channel is accessed, nothing happens. You can see in the log that an attempt is being made to open the channel. Then nothing happens for a long time until the client cancels the stream. I would expect Stream Master to timeout after a while and try to load a backup channel.

**Stream Master Info**
- Version Number: 0.14.6.0

**Link to logs (required)**
`info: System.Net.Http.HttpClient.Default.ClientHandler[100]
 Sending HTTP request GET http://192.168.1.37test/itv.php?cmd=http://localhost/ch/455045_`

**Comment by Jakyrian** [comment]
Update the container and make sure you're running 0.15.0.60+. Backup streams should be working.

**Comment by SenexCrenshaw** [comment]
try latest
