### ISSUE TITLE
Feature Request: HdHome Run import

### ISSUE THREAD

**Issue by IllMethods** [SenexCrenshaw/StreamMaster#249]
Hello

I'd like to be able to import my hdhomeruns into stream master and then give access via stream master. reason being is so I can easily have my paid channels and freeview all on the same virtual hdhome runs. This way, the channels that are actually on freeview and paid tv can be accessed from the hdhome run and have the m3u imports as backups

**Comment by Jakyrian** [comment]
This is possible already, just add http://<hdhomerun_IP>/lineup.m3u to SM as an M3U and it'll populate your HDHR channels

**Comment by IllMethods** [comment]
Lol yeah sorry, I figured it out. I didn't know I could do that with my hd home run
