### ISSUE TITLE
Feature Request: Incorporate Schedules Direct API

### ISSUE THREAD

**Issue by SenexCrenshaw** [SenexCrenshaw/StreamMaster#25]
**Is your feature request related to a problem? Please describe.**
I want an EPG option to use the Schedule Direct API. 

**Describe the solution you'd like**
I want an editor so I can select my lineups and channels from Schedule Direct
SM will use that API to populate the EPG list

**Comment by xtinct101** [comment]
This would be amazing for anyone using SD
