### ISSUE TITLE
Feature Request: Postgres_ENV_FILE Support

### ISSUE THREAD

**Issue by Ttfgggf** [SenexCrenshaw/StreamMaster#251]
**Is your feature request related to a problem? Please describe.**
Yes. So Support for POSTGRES_ENV_FILE Options within streammaster

**Describe the solution you'd like**
I would like to be able to use secrets with the POSTGRES Environment Variables below.

POSTGRES_USER={USER_HERE}
POSTGRES_PASSWORD={PASSWORD_HERE}
POSTGRES_HOST={HOST_HERE}
POSTGRES_DB=

**Describe alternatives you've considered**
Have already tried POSTGRES_USER_FILE but it doesn't work with docker or podman secrets.

**Additional context**
It defaults to the postgres user even if I have specified on in POSTGRES_USER_FILE

**Comment by Ttfgggf** [comment]
See here regarding what I mean https://github.com/SenexCrenshaw/StreamMaster/issues/217#issuecomment-2080621813

**Comment by SenexCrenshaw** [comment]
Its in the latest 0.17.1
The files should just have either user name or password. nothing else in there. 
docs
https://senexcrenshaw.github.io/StreamMaster/GettingStarted/#step-1-create-the-docker-compose-file
