### ISSUE TITLE
Bug: Stream Group URLs change on every reboot

### ISSUE THREAD

**Issue by wongchristopher** [SenexCrenshaw/StreamMaster#253]
**Describe the Bug**
When running StreamMaster for the first time the settings.json file will not be saved to the file system unless you save something on the settings page.  

This causes ServerKey to change every time it's restarted which changes all the secure URLs for StreamGroups.

If you are running into this go into the settings page change something and save it.  It should force StreamMaster to save the settings.json file.  

**Stream Master Info**
0.14.6.0

**Comment by Jakyrian** [comment]
This was fixed, update the container and make sure you're running 0.15.0.60+
