### ISSUE TITLE
Bug: when adding a new m3u url, the system returns following error : "The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing"

### ISSUE THREAD

**Issue by jackydec** [SenexCrenshaw/StreamMaster#256]
when adding a new m3u url, the system returns following error : "The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing"

**Stream Master Info**
0.15.0

**Link to logs (required)**
- Upload any relevant logs here [Gist](http://gist.github.com). _Do not upload attachments_.

**Comment by SenexCrenshaw** [comment]
try latest
