### ISSUE TITLE
Bug: ERROR:  relation "ChannelGroups" already exists

### ISSUE THREAD

**Issue by Crosus97** [SenexCrenshaw/StreamMaster#258]
**Describe the Bug**
When Watchtower update this afternoon, the streamaster, didn't start anymore, and launch this logs errors

**Stream Master Info**
- latest, probably 0.60

**Link to logs (required)**
- https://gist.github.com/Crosus97/08057816c47ef3e5bfc82a9ca2ec18aa

**Comment by thebatfink** [comment]
Where you prviously using the channels releases? If not, then the update to the latest tag is a breaking change (its mentioned in discord but not git) and it requires starting from fresh with an empty config volume / setting everything up from scratch again.

**Comment by wingede** [comment]
I've encountered this also with a fresh clean install and copying to a new test container.  I've been doing this for quite some time until just recently (around the merge to main).

**Comment by Crosus97** [comment]
i restore a backup, but what i need to do to pass this update?

**Comment by thebatfink** [comment]
What version is the back from, what tag were you using before

**Comment by Crosus97** [comment]
i have the lastest version always, i have a backups with 
![image](https://github.com/user-attachments/assets/1a59ba3a-bfef-42c8-8c87-f991a0a6e0c4)

at 17:00 gmt+2 work perfectly

at 21:00 gmt+2 the container didn't start after a update of watchtower

when i entered on the docker versions, i find a "updated" lastest

**Comment by Crosus97** [comment]
can you tell me the "last" latest? pls
to select that version i neeed for this night

**Comment by Crosus97** [comment]
ok, i install the 0.14.5 and my streamaster work, what i need to do to upgrade it?

**Comment by thebatfink** [comment]
Yes so, ‘latest’ wasn’t the latest for the last 10 months as he was working on ‘channels’ rewrite. The other day the channels rewrite was merged and became the new latest. I do not believe it is possible to upgrade in place from 14 to 15. You’ll need to start fresh (clear your config volumes) and start from scratch with a pull of latest.

**Comment by Crosus97** [comment]
i downgrade to 14.0 and now im installing new version 15.0 and configuring

thank you for the support
