### ISSUE TITLE
Bug: ffmpeg launched with different arguments than those specified in custom profile

### ISSUE THREAD

**Issue by Aladex** [SenexCrenshaw/StreamMaster#263]
**Describe the Bug**  
The Stream Master UI displays that `ffmpeg` is being launched with the parameters specified in the custom profile. However, when inspecting the running container, the `ffmpeg` process is started with different arguments than what is shown in the UI.

**Stream Master Info**  
- Version Number: `channels-0.15.0.60` (Docker image: `senexcrenshaw/streammaster:channels-0.15.0.60`)

Unfortunately, I do not have direct logs, but I’ve attached screenshots showing the discrepancy between the UI and the actual process arguments.

![Screenshot_20241025_162120](https://github.com/user-attachments/assets/50bf980d-281b-450d-b9a9-ce38bcea88eb)

**Steps to Reproduce:**
1. Run the StreamMaster instance using the Docker image `senexcrenshaw/streammaster:channels-0.15.0.60`.
2. Configure a custom `ffmpeg` profile in the UI.
3. Start a stream.
4. Enter the container and check the `ffmpeg` process with `ps aux | grep ffmpeg`.
5. Observe that the running `ffmpeg` process does not match the parameters defined in the UI profile.

**Expected Behavior**  
`ffmpeg` should launch with the parameters defined in the custom profile set in the UI.

**Additional Context**  
It appears the custom profile isn't correctly applied to the running `ffmpeg` process, causing a mismatch.

**Comment by Aladex** [comment]
**An important clarification**: if you select the profile not in the stream group but in the m3u file and its settings, it applies correctly, and ffmpeg runs with the correct parameters.

**Comment by gettenrich** [comment]
Any chance you can point me in the right direction to get ffmpeg set up along side stream master? I basically want to remux the streams mpegts to mkv. That is, if I understand it correctly. I have a couple devices that do not like mpegts.

**Comment by Aladex** [comment]
Well, I'm not sure I can help much. I managed to set up a profile for the m3u8 file. You press the button with the profiles, set your parameters, give it a new name. Then go to the right panel with channels, click on source editing (not the stream group, but m3u8), and set the ffmpeg profile for it. That's the only way it worked for me.

**Comment by SenexCrenshaw** [comment]
here is a good spot to look for some examples
https://discord.com/channels/1075403862124531753/1296815673472974878
