### ISSUE TITLE
Bug: Warning in /config/logsettings.json

### ISSUE THREAD

**Issue by ruiribeiro2010** [SenexCrenshaw/StreamMaster#268]
**Describe the Bug**
Warning: /config/logsettings.json does not exist and will not be included in the backup.

**Stream Master Info**
- Version Number: 0.15, 0.16, 0.16.1

**Link to logs (required)**
- Upload any relevant logs here [Gist](http://gist.github.com). _Do not upload attachments_.

**Comment by SenexCrenshaw** [comment]
fixed in latest

**Comment by ruiribeiro2010** [comment]
> fixed in latest

Hello, thank you

but it keeps showing the same warning.

I've already uninstalled it, installed it again, and the logo shows

Warning: /config/logsettings.json does not exist and will not be included in the backup.

**Comment by ruiribeiro2010** [comment]
Hello???

**Comment by Jakyrian** [comment]
I mean is this really a problem? I do see the same line in my log, specifically:
`Backup Output: Starting backup process...
Database backup completed: db_2024-11-03_08-53-32.gz
Warning: /config/logsettings.json does not exist and will not be included in the backup.
Directories and files backup completed: files_2024-11-03_08-53-32.tar.gz`
All it means is that logsettings.json does not exist so it doesn't need to be included. Whether this file actually gets created or not, I'm unsure at this point. My setup does not have that file and likely never has.

**Comment by ruiribeiro2010** [comment]
Hello, I don't know if it's an error or not.

In fact, this file is not created, shouldn't it be??
Best regards

**Comment by ruiribeiro2010** [comment]
ok, thanks
