### ISSUE TITLE
Bug: StreamMaster is exceeding the ScheduleDirectAPIService limit with a 429 error

### ISSUE THREAD

**Issue by Jakyrian** [SenexCrenshaw/StreamMaster#274]
**Describe the Bug**
Seemingly StreamMaster is not adhering to the API limit, which causes a "429 Too Many Requests" error to be thrown. This then leads to a timeout with the following message: "Maximum image downloads reached. Counter resets every 24h."

**Stream Master Info**
- 0.17.3.0

**Link to logs (required)**
    fail: StreamMaster.SchedulesDirect.SchedulesDirectAPIService[0]
          /20141201/image/1b0f0cefe171f6bd5f37bb9ec8003edf2890ee892ae53aed6ffb1e63d9585a6b.jpg: 429 Too Many Requests : Token=xxxxx...
    response=
    MAX_IMAGE_DOWNLOADS
    code=
    5002
    serverID=
    20141201.web
    message=
    Maximum image downloads reached. Counter resets every 24h. Post message to http://forums.schedulesdirect.org/viewforum.php?f=6
    datetime=
    2024-11-03T14:37:47Z

Issue reported by healy903 and cheese24 in the Discord.

**Comment by healy93** [comment]
Not sure if this helps but users have reported this on xteve too "Thanks to Gary over at EPG123 forum it seems Xteve was set to cache images and tried to download thousands all at once. Removing this seems to have resolved and am not hitting a limit now!" Any way to turn off cache?

**Comment by healy93** [comment]
> That’s good news that it’s not SM specific. If you have a link to that forum post, I can imagine it’ll be helpful

Unfortunately I don't have a link to the original post, this was just a comment in the SD forums

**Comment by healy93** [comment]
https://www.thegreenbutton.tv/forums/viewtopic.php?t=13837&sid=9391ccc437fa16d605cea299c126a317&start=40

**Comment by SenexCrenshaw** [comment]
Fixed in latest
