### ISSUE TITLE
Feature Request: Allow local file paths for Playlist and EPG sources

### ISSUE THREAD

**Issue by joshjryan** [SenexCrenshaw/StreamMaster#277]
**Is your feature request related to a problem? Please describe.**
Currently the file inputs require you to provide a URL or to directly upload a file. I have have a few scripts that generate my m3u and epg files, and they write them to a path that is available to the SM docker container. I'd like to be able to point directly to that path (e.g. `/data/channels.m3u` or `/data/epg1/xmltv.xml`).

**Describe the solution you'd like**
Allow paths to local files in the current inputs.

**Describe alternatives you've considered**
For now I've just manually copied files into `/config/Playlists/M3U`, but that's messy and when I do that I'm unable to configure the playlist to use a different field for unique ID.

**Additional context**
![image](https://github.com/user-attachments/assets/984c7ec7-f1aa-4eb1-81ef-51ec9c636b2c)

**Comment by SenexCrenshaw** [comment]
they are local. its docker and under your mapped config directory. just  overwrite the files and send an api request to update or bounce the container.

**Comment by FloydKulis** [comment]
@joshjryan 
I have the same problem as you. Did you manage to solve it?
I tried to do it this way, but unfortunately after refreshing the file in StreamMaster, no changes are visible.
![image](https://github.com/user-attachments/assets/45a0cfab-0545-4978-a254-db6f6368b0a7)
