### ISSUE TITLE
Feature Request: M3U to STRM

### ISSUE THREAD

**Issue by mitch91175** [SenexCrenshaw/StreamMaster#288]
Would be awesome to be able to geenrate STRM files from SG and sync when the URL changes in the STRM file.

This feature would write the file to a user specified directory for 3rd party consumption.

https://github.com/mwlistscom/GetSTRM/blob/main/GetSTRM.go

**Comment by ashipaek0** [comment]
This could be useful for providers that also have movies and tv shows in their m3u

strm could be use to populate a library for media servers

**Comment by mitch91175** [comment]
@ashipaek0 this has been implemented in the latest .net9 release. So far so good with generating the files. If you use make sure to update the setting for the URL is necessary.

**Comment by ashipaek0** [comment]
> @ashipaek0 this has been implemented in the latest .net9 release. So far so good with generating the files. If you use make sure to update the setting for the URL is necessary.

wow, didn't notice that.

this build:  senexcrenshaw/streammaster:net9-0.17.10.13    ?
