### ISSUE TITLE
Bug: clicking on a group doesn't select it/ shows its streams on the right

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#31]
clicking on a group doesn't select it/ shows its streams on the right

**Stream Master Info**
- latest nightly

**Link to logs (required)**
can't share it has my url on it

**Comment by SenexCrenshaw** [comment]
Please check if this is still broke in the latest image

**Comment by aniel300** [comment]
i believe it is not, thanks

**Comment by SenexCrenshaw** [comment]
provide an example please. Pictures work nicely

**Comment by aniel300** [comment]
> provide an example please. Pictures work nicely

sorry i meant to say it is fixed, sorry.

**Comment by aniel300** [comment]
ok, to be honest, now it doesn't select it but it still doesn't show it on the right. but am not to worried about this at the moment
