### ISSUE TITLE
Bug: no real time refresh on the webui

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#32]
**Describe the Bug**
db needs to be deleted for changes/deleted channels/groups, etc from the backend for SM to update accordingly on its webui. 

**Stream Master Info**
- latest nightly 

**Link to logs (required)**
- can share only in private if needed since am afraid of leaking myu personal ip, info, etc

**Comment by SenexCrenshaw** [comment]
Please check if this is still broke in the latest image

**Comment by aniel300** [comment]
> Please check if this is still broke in the latest image

is way better but there still room for improvement.

**Comment by aniel300** [comment]
@SenexCrenshaw this still works. it still not updating the groups/ channels accordingly. it doesn't add the news ones or delete the old/ deleted ones. please can u reopen the post or do u want me to create a new one?

**Comment by SenexCrenshaw** [comment]
I just need a list of each item you found broke and i can address them from there.

**Comment by aniel300** [comment]
i also forgot to mention that when deleting the db then channels and groups get updated as they are supposed to

**Comment by aniel300** [comment]
did u do any improvements to this with the latest stable?

**Comment by aniel300** [comment]
can confirm issue is either fixed in my quick/ recent testing

**Comment by aniel300** [comment]
ok it now deletes the groups/channels but for some reason it now doesn't show the remaining channels (it does show the groups)
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/e33f82e9-8d98-46f6-a21c-fad8bd5508df)

**Comment by aniel300** [comment]
never mind
