### ISSUE TITLE
Bug: ms crashes when trying to play a non working link/url

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#34]
**Describe the Bug**
ms crashes when trying to play a non working link/url

**Stream Master Info**
- latest stable

**Link to logs (required)**
- happy to provide them on private

**Comment by SenexCrenshaw** [comment]
Please check if this is still broke in the latest image

**Comment by aniel300** [comment]
yep i believe it has been fixed, thanks.

**Comment by SenexCrenshaw** [comment]
excellent!
