### ISSUE TITLE
Feature Request: XC API

### ISSUE THREAD

**Issue by Hobbs1210** [SenexCrenshaw/StreamMaster#35]
I'm writing to request the addition of XC API integration. This enhancement would greatly enhance the compatibility of your software with many popular IPTV apps available on the market.

**Comment by SenexCrenshaw** [comment]
Excellent addition!

**Comment by SenexCrenshaw** [comment]
I cannot find a good source of information for this API.... Any help would be appreciated.

**Comment by Hobbs1210** [comment]
> I cannot find a good source of information for this API.... Any help would be appreciated.

This client implementation should help you. 
https://github.com/Fazzani/Xtream.Client

**Comment by aniel300** [comment]
i would love for this feature as well

**Comment by sgottscho** [comment]
This would be great as many providers are not supply m3us, only XC logins. Current provider even has it blocked to generate m3u from xstream codes api. I am using IPTV editor to convert currently, but would be able to eliminate the use IPTV editor if this was added.

**Comment by aniel300** [comment]
> XC logins

have u tried downloading the m3u?

**Comment by sgottscho** [comment]
> > XC logins
> 
> have u tried downloading the m3u?

Like I mentioned my current provider does provide m3u link to download. Only xStream Code logins. Usually you can still download a m3u following this format

http://1.1.1.1.com:1111/get.php?username=usernamehere&password=passordhere&type=m3u

But my provider has that blocked.

I am currently using IPTV Editor which can use either m3u files or XC them republishes to another m3u file, which I am then importing into Stream Master. If Stream Master was able to use XC logins I would be able to cut IPTV editor out my workflow.

**Comment by aniel300** [comment]
> > > XC logins
> > 
> > 
> > have u tried downloading the m3u?
> 
> Like I mentioned my current provider does provide m3u link to download. Only xStream Code logins. Usually you can still download a m3u following this format
> 
> http://1.1.1.1.com:1111/get.php?username=usernamehere&password=passordhere&type=m3u
> 
> But my provider has that blocked.
> 
> I am currently using IPTV Editor which can use either m3u files or XC them republishes to another m3u file, which I am then importing into Stream Master. If Stream Master was able to use XC logins I would be able to cut IPTV editor out my workflow.

have u tried this combinations?

http://serverurl:port/get.php?username=xxx&password=xxx&type=m3u_plus
http://serverurl:port/get.php?username=xxx&password=xxx&type=m3u_plus&output=mpegts
http://serverurl:port/get.php?username=xxx&password=xxx&type=m3u_plus&output=ts

**Comment by SenexCrenshaw** [comment]
will reopen if i can find docs on how to implement.

**Comment by Dont-ask-for-it** [comment]
Any chance you'll implement it?
