### ISSUE TITLE
Bug: Unable to remove additional streams when "editing a stream"

### ISSUE THREAD

**Issue by nlitend1** [SenexCrenshaw/StreamMaster#37]
**Describe the Bug**
I AM able to add "additional streams" in the stream editor. 
I am NOT able to remove the additional stream. The edit/save button flashes for only a split second and then is grayed out/unable to save the changes. 

**Stream Master Info**
- Latest (pulled today)

**Link to logs (required)**

happy to provide privately

**Comment by xtinct101** [comment]
Going to add to this instead of starting a new thread. Could you also please include the OG stream associated with the stream you're editing listed in the "Selected" column so you can set priorities of which stream to play first.

**Comment by nlitend1** [comment]
Great point. I wonder if they are able to be prioritized or if they are just a backup to the first stream. Being able to set priority would be a GREAT feature , and yes would definitely need to know which playlist/source is which lol.

**Comment by xtinct101** [comment]
before the new system change, you could prioritize streams. I spoke with @SenexCrenshaw regarding adding this feature back and he seemed open to it.

**Comment by SenexCrenshaw** [comment]
Ill work on this next.

**Comment by SenexCrenshaw** [comment]
You can prioritize once again. If the OG stream has a URL than that will always be the first in the Rank though. The others you can drag around to rank them.

Check the latest build.

**Comment by xtinct101** [comment]
Amazing turn around as always!
Will check it out. Any reason you’re opposed to being able to set the priority for any of the streams, including the OG one?

**Comment by SenexCrenshaw** [comment]
You can do the additional ones. Og is always first. Otherwise just pick the
one you want first?

I might be missing the use case though.

**Comment by xtinct101** [comment]
You’re not, it’s for ease of use only.

**Comment by SenexCrenshaw** [comment]
Im going to keep this as is. If you want to modify the OG one than create a new stream and assign them to it.
