### ISSUE TITLE
Bug: .ts streams not working in ui videoplayer

### ISSUE THREAD

**Issue by mLgz0rn** [SenexCrenshaw/StreamMaster#39]
**Describe the Bug**
The videoplayer in the webui only plays m3u8 streams and does not work with .ts streams.
When clicking on an epg item the entire player and epg disappears and a never ending loading circle shows up at the top of the screen

We discussed this in discord, just wanted to open an issue here.

**Stream Master Info**
- 2.0.12

**Link to logs (required)**
- Upload any relevant logs here [Gist](http://gist.github.com). _Do not upload attachments_.
Nothing relevant is showing up in logs

**Comment by aniel300** [comment]
am also having this issue

**Comment by SenexCrenshaw** [comment]
the video player has been discontinued for now.
