### ISSUE TITLE
Feature Request: add option to select logo from EPG

### ISSUE THREAD

**Issue by xtinct101** [SenexCrenshaw/StreamMaster#44]
**Is your feature request related to a problem? Please describe.**
Selecting a logo from an EPG requires you to know the name of the logo you're looking for. 

**Describe the solution you'd like**
Add a button in the logo drop down to auto use the logo from EPG.

![logo](https://github.com/SenexCrenshaw/StreamMaster/assets/89475753/d1907149-6e16-495a-90f4-ea64fe6fc978)

**Comment by SenexCrenshaw** [comment]
Channels (EPG File) have no tie to M3U Streams. I cache the icons from the epg/channel entries and thats about it. 

I could have an auto match button that will try to use some smarts to match channel and stream names and then set icons/epgs accordingly.

Thoughts?

**Comment by xtinct101** [comment]
I don’t think we need it to be automatic. 

Here’s an example: 
For stream A, I assign “ABC” as the EPG for that stream. I then go to the logo drop-down and there would be a button to use the logo, if available, from the EPG selected for that stream.  In this case “ABC” EPG.

you mention you cache the logos/icons but you must keep a reference of where they come from?

**Comment by SenexCrenshaw** [comment]
Done
