### ISSUE TITLE
Bug: Episode appears in Emby as NEW when it is a repeat.

### ISSUE THREAD

**Issue by infosecmatters2021** [SenexCrenshaw/StreamMaster#47]
Issue: Emby shows all episodes as "New" when many are actually repeats. See Emby-EPG-Shows-NEW-for-episode
Cause: I believe the "< new />" code should not be added to all episodes. 

Difference:
See Original-EPG-XMLTV file. No < new /> or < previously-shown />
See Streammaster-EPG-XMLTV - contains both < new /> and < previously-shown />
See StationAirings to see results from TMS - shows original air date. This is not a new episode.

[StationAirings.txt](https://github.com/SenexCrenshaw/StreamMaster/files/11926777/StationAirings.txt)
<img width="840" alt="Emby-EPG-Shows-NEW-for-episode" src="https://github.com/SenexCrenshaw/StreamMaster/assets/85263005/345c2975-e7c3-4321-afb4-552f4891bc95">
<img width="826" alt="Streammaster-EPG-XMLTV" src="https://github.com/SenexCrenshaw/StreamMaster/assets/85263005/af110240-f4c9-4d20-99e1-70239b299d19">
<img width="887" alt="Original-EPG-XMLTV" src="https://github.com/SenexCrenshaw/StreamMaster/assets/85263005/fced8d57-da94-41d9-9a17-127a2a11b053">

**Comment by SenexCrenshaw** [comment]
Check the latest image. I add in Live and Premiere and fixed it so they will only show if they are in the original epg.

**Comment by infosecmatters2021** [comment]
My original XMLTV file contains new, live and premiere. The new and live codes are removed from the streammaster XML file. I'm not certain if it is due to being a single statement (e.g., < new /> - space before new so it would still appear in this comment. It's not "< new>< /new> or < live>< /live> - spaced added before each"
Premiere works as it is (space added so it appears here) "< premiere>Premiere< /premiere>".

I am using the latest build.

<img width="1427" alt="Streammaster-no-live-or-new" src="https://github.com/SenexCrenshaw/StreamMaster/assets/85263005/d37fcd6b-8ff5-4a47-9c76-5037fa2d4b35">
<img width="1727" alt="new_and_live" src="https://github.com/SenexCrenshaw/StreamMaster/assets/85263005/090187e0-caa6-44ee-83ad-86919bc60449">

**Comment by SenexCrenshaw** [comment]
Can you give me a copy of the EPG you are using? That would accelerat
getting this to work.

**Comment by infosecmatters2021** [comment]
XMLTV file with new, live and premiere entries.
[epg.xml.zip](https://github.com/SenexCrenshaw/StreamMaster/files/11931988/epg.xml.zip)

**Comment by infosecmatters2021** [comment]
Was the XML file helpful? Should we leave this in closed status or would you like it re-opened?

**Comment by Austin1** [comment]
I think maybe this issue is related to the issues i'm having. I can't get Emby to read my EPG data at all. Here is a direct snippet from the raw XML, pre SM:
```
<programme start="20231004020100 +0000" stop="20231004030000 +0000" start_timestamp="1696384860" stop_timestamp="1696388400" channel="WPVI" >
		<title>The Golden Bachelor</title>
		<desc>Twenty-two incredible women, ranging in age from 60 to 75, step into the spotlight in the hope of finding lasting love with golden bachelor Gerry Turner.</desc>
</programme>
```

SM Formatted:
```
  <programme channel="WPVI" start="20231004020100 +0000" stop="20231004030000 +0000">
    <audio />
    <credits />
    <desc>Twenty-two incredible women, ranging in age from 60 to 75, step into the spotlight in the hope of finding lasting love with golden bachelor Gerry Turner.</desc>
    <icon height="" src="" width="" />
    <language />
    <rating />
    <sub-title />
    <title>The Golden Bachelor</title>
    <video />
  </programme>
  ```
I attempted to run each of these snippets through xmltv.exe validate function and got errors on both :/

```cmd
C:\Users\Austin\Desktop\xmltv-1.2.1-win64>xmltv.exe tv_validate_file  "cdn example.xml"
Timezone is -0700
The file is not valid according to the xmltv dtd:
 cdn%20example.xml:1: validity error : No declaration for attribute start_timestamp of element programme
cdn%20example.xml:1: validity error : No declaration for attribute stop_timestamp of element programme

The file did not validate as well-formed XML, so no further
processing was performed.

C:\Users\Austin\Desktop\xmltv-1.2.1-win64>xmltv.exe tv_validate_file  "sm example.xml"
Timezone is -0700
The file is not valid according to the xmltv dtd:
 sm%20example.xml:1: validity error : Element programme content does not follow the DTD, expecting (title+ , sub-title* , desc* , credits? , date? , category* , keyword* , language? , orig-language? , length? , icon* , url* , country* , episode-num* , video? , audio? , previously-shown? , premiere? , last-chance? , new? , subtitles* , rating* , star-rating* , review* , image*), got (audio credits desc icon language rating sub-title title video )
sm%20example.xml:7: validity error : Element rating content does not follow the DTD, expecting (value , icon*), got

The file did not validate as well
```

**Comment by Austin1** [comment]
well... in my attempts to make the above analysis.... I refreshed my EPG in SM back end and now I'm seeing results in Emby.. sooo... probably mostly user error for me
