### ISSUE TITLE
Feature Request: ability to include or not include things like "channel-number, tvg-chno, etc in the m3u output/link"

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#49]
**Is your feature request related to a problem? Please describe.**
yes to https://github.com/SenexCrenshaw/StreamMaster/issues/8

**Describe the solution you'd like**
ability to include or not include things like "channel-number, tvg-chno, etc in the m3u output/link"

**Describe alternatives you've considered**
n/a

**Additional context**
i need this because i use emby built in guide/epg provider and i match the channels by using "tvg-id"

**Comment by SenexCrenshaw** [comment]
What exactly should be omitted? Or even better if you have an example line on what this should look like.

**Comment by aniel300** [comment]
well we never got to pinpoint the issue because a new issue was introduced while trying to ts this one but for right now i would like to omit "channel-number" and "tvg-chno" from the m3u

**Comment by aniel300** [comment]
> well we never got to pinpoint the issue because a new issue was introduced while trying to ts this one but for right now i would like to omit "channel-number" and "tvg-chno" from the m3u and give that a try


well we never got to pinpoint the issue because a new issue was introduced while trying to ts this one but for right now i would like to omit "channel-number" and "tvg-chno" from the m3u and give that a try

**Comment by SenexCrenshaw** [comment]
Check out the latest image. I included a M3U Settings section (in settings) where you can turn fields on/off in the M3U output.

**Comment by aniel300** [comment]
> Check out the latest image. I included a M3U Settings section (in settings) where you can turn fields on/off in the M3U output.

perfect let me give this a try

**Comment by aniel300** [comment]
> Check out the latest image. I included a M3U Settings section (in settings) where you can turn fields on/off in the M3U output.

so it seems that when imported channels that dont include a tvg-id value on them they get assigned (tvg-id="dummy") which emby doesn't like it i believe therefore all the channels/groups don't show up. is there something u can do something about this. i think this is the last culprit since i was able to get channels to match with the M3U Settings section that u added to the settings menu now getting all the groups/ channels to show up is the last thing to make it perfect.

**Comment by SenexCrenshaw** [comment]
Yep. I'll add a setting in the m3u to turn that on or off per m3u.

**Comment by aniel300** [comment]
> Yep. I'll add a setting in the m3u to turn that on or off per m3u.

is that going to work? remember i still need the tvg-id to be enabled and to show up for the desired channels but for the rest of them that don't have a valued (basically the rest of the channels/ groups except my custom groups/channels) need to be ignore or omitted (no (tvg-id="dummy"))

**Comment by SenexCrenshaw** [comment]
The settings will control if any epg ID not set will be set to dummy or
just excluded.

Thoughts?

**Comment by aniel300** [comment]
yep that will do the trick if am not mistaking

**Comment by aniel300** [comment]
@SenexCrenshaw am assuming u implemented this? am trying the new build now

**Comment by aniel300** [comment]
where in the settings or where can i find this implementation in the webui?

**Comment by SenexCrenshaw** [comment]
Give it a shot

**Comment by aniel300** [comment]
i have fully tested but i took a peak at the sm m3u file and yes now it seems to be a almost 1:1 copy of how the iptv editor is therefore it should now works on my emby. am about to fully test this.
