### ISSUE TITLE
Feature Request: ability to match channel using https://www.tvchannellists.com/w/Main_Page

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#50]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
ability to match channel using https://www.tvchannellists.com/w/Main_Page, i currently do it manually, and it is is only done once but if i switch provider then i would have to do it again manually and is a little time consuming

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by SenexCrenshaw** [comment]
I dont see an api for this. I would need something I could query. To build my own would need a LOT Of upvotes and support.

**Comment by aniel300** [comment]
fair enough and don't worry it is only around 300 channels and i can still can do that manually. thanks for the reply and willingness
