### ISSUE TITLE
Feature Request: built in link checker with automatic run and auto hide/delete channel

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#51]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
ability to have sm scan for all the channels links automatically/periodically and auto hide and/or delete dead ones.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by SenexCrenshaw** [comment]
I plan on implementing stream health in a later patch that will track streams as they are used. To do this proactively could be a mess. Some folks have 40k+ streams.

**Comment by aniel300** [comment]
um ok and yes, as they are being used could also work. thanks. any eta for this? (no rush)
