### ISSUE TITLE
Bug: unable to see the check marks across the ui

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#52]
**Describe the Bug**
unable to see the check marks across the ui. I also tried a different browser.

**Stream Master Info**
- latest nighty available 

**Link to logs (required)**
- screenshot
![chrome_XqrMAWMMsy](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/f3b1f3bd-5163-4a1d-9e55-06ac17b3ca71)

**Comment by mLgz0rn** [comment]
What checkmarks? Don't think there is suppose to be any there

**Comment by SenexCrenshaw** [comment]
there are no checkboxes for that screen. Is this still an issue?

**Comment by aniel300** [comment]
> there are no checkboxes for that screen. Is this still an issue?

yes there are screen on the left side and on the right side unless u changed it recently and i didnt notice.

**Comment by aniel300** [comment]
did u took away check marks from the webui?

**Comment by SenexCrenshaw** [comment]
From some that wasn't used. The ui is still developing....

**Comment by aniel300** [comment]
i cant or dont see the checkmarks on webui at all

**Comment by SenexCrenshaw** [comment]
I patched this in the latest build.

**Comment by aniel300** [comment]
yep i noticed. i thought i closed this but apparently not. anyways thank u very much
