### ISSUE TITLE
Bug: status page showing last used channel being active despite sm not being used at the moment

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#54]
**Describe the Bug**
there this behavior where some times sm is not being used at all yet the last used channels can be seen being used in the "status" page. this happens every so often. any thoughts on this? 

**Stream Master Info**
- latest nightly available

**Link to logs (required)**
- n/a

**Comment by SenexCrenshaw** [comment]
Should be fixex in the latest image

**Comment by aniel300** [comment]
perfect thank you, will test and report back

**Comment by aniel300** [comment]
still getting some strange b heavior from sm, the "xxx" is not being played anywhere at the moment 
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/27f8eb4d-8bad-4cd0-984d-2d40fd859517)
