### ISSUE TITLE
Feature Request: ability to change channels order based on the channel id order in the webui

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#56]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
ability to change channels order using the "auto set" based on the channel id order in the webui

**Describe alternatives you've considered**
n/a 

**Additional context**
n/a

**Comment by SenexCrenshaw** [comment]
It which editor are you trying to do this? Pics work!

**Comment by aniel300** [comment]
this one. let me know if this screenshot works
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/fd107857-9fc1-4ca1-a6a3-6d31c4e58ed8)

**Comment by SenexCrenshaw** [comment]
Do you mean just ordering the ID column?? This is in there now

**Comment by aniel300** [comment]
am talking about at the db level but idk if this will be a good idea

**Comment by SenexCrenshaw** [comment]
The channel id is from the DB. It gets assigned as each entry is added.

**Comment by aniel300** [comment]
so the current implementation of this is working as design?

**Comment by aniel300** [comment]
need more input from you on this to make sure we are in the same page. then find out if this sm can do this and if not then maybe implement a solution/ workaround.

**Comment by SenexCrenshaw** [comment]
do you mean channel order in the exported m3u and epg?

**Comment by aniel300** [comment]
yes and i think a possible solution or workaround would be this: https://github.com/SenexCrenshaw/StreamMaster/issues/102

**Comment by SenexCrenshaw** [comment]
You can sort by channel id now

**Comment by aniel300** [comment]
will test and report back, thanks you.
