### ISSUE TITLE
Feature Request: ability to edit "tvg-id", etc from the webui

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#57]
**Is your feature request related to a problem? Please describe.**
ability to edit "tvg-id",etc from the webui

**Describe the solution you'd like**
ability to edit "tvg-id",etc from the webui as needed

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by SenexCrenshaw** [comment]
What do you mean by edit? The drop down covers dummy and any other channels from a provided epg. Did you also want the ability to just type in any text into the field?

**Comment by aniel300** [comment]
> What do you mean by edit? The drop down covers dummy and any other channels from a provided epg. Did you also want the ability to just type in any text into the field?

yes ples, i need this because i match myb local channels to the over the air epg in emby and they use "x.x" numbers

**Comment by aniel300** [comment]
does the "tvg-id" has anything to do with the epg? i thought the both represented different things.
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/c7423b04-ede4-4564-b125-99c0c4ac53fd)
