### ISSUE TITLE
Bug: unable to proxy from a given provider

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#58]
**Describe the Bug**
unable to proxy from a given provider

**Stream Master Info**
- latest nightly available
-  
**Link to logs (required)**
- happy to share on private

**Comment by SenexCrenshaw** [comment]
Any errors??

**Comment by aniel300** [comment]
an trying to play the same same channel which works with others provider but this one starts to buffer

**Comment by aniel300** [comment]
another provider is doing the same thing

**Comment by aniel300** [comment]
i think it is just the provider that is bad/ kick ny stream
