### ISSUE TITLE
Bug: some observation 

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#66]
**Describe the Bug**
i currently use iptveditor but am planning to switch to sm sooner than later.  i notice some spacing in the m2u formating of sm compared to iptvedito and i was wondering if this makes any difference

**Stream Master Info**
- latest stable version

**Link to logs (required)**
- sm m3u screenshots:
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/2e47f8ac-1189-4b2d-9621-ba7a6516a863)
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/75da385e-6047-483f-83b5-20135ae993fb)

iptveditor screenshots: 
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/5ed99f32-fbf4-4b00-a127-b41e11e5ed75)
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/790d8757-4a19-4bd0-90db-9af3e5bbd9a5)

when importing a sm m3u back into iptveditor for some of the channel i get this strange naming: 
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/7dd2009b-71c4-4ad1-8cf9-334b0e4e0801)

**Comment by SenexCrenshaw** [comment]
I patched this in the latest build.

**Comment by aniel300** [comment]
perfect, thank u very much. will check out later on tonight
