### ISSUE TITLE
Feature Request: how does the fail over works?

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#67]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
is it base on the channel being down, high ping, latency or buffering. it would be nice if the fail over would switch channels depending on this parameters (down, high ping, latency or buffering)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by SenexCrenshaw** [comment]
Right now it only moves to the next stream if it fails or from an API call. I do plan on implementing some stream health checks and will incorporate that as SM is being developed. Right now though, its down only.

**Comment by aniel300** [comment]
perfect, please keep up the good work. any eta for this (no rush)
