### ISSUE TITLE
Bug: cant go to "http://xxx:7095/editor/streamgroup" sm crashes.

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#69]
**Describe the Bug**
cant go to "http://xxx:7095/editor/streamgroup" sm crashes.. this is happening when i gave sm 19k channels to work with

**Stream Master Info**
- latest stable

**Link to logs (required)**
- n/a

**Comment by mLgz0rn** [comment]
It's fixed, update to latest

**Comment by aniel300** [comment]
ok thanks, let me try that

**Comment by SenexCrenshaw** [comment]
Yeah. You guys are quick!

**Comment by aniel300** [comment]
> It's fixed, update to latest

that fixed

**Comment by mLgz0rn** [comment]
> > It's fixed, update to latest
> 
> that fixed

Just be aware that senex has changed the update interval for epg and m3u files from days to hours.
m3u has a visual bug, it still says days, but it's actually hours.

**Comment by aniel300** [comment]
> > > It's fixed, update to latest
> > 
> > 
> > that fixed
> 
> Just be aware that senex has changed the update interval for epg and m3u files from days to hours. m3u has a visual bug, it still says days, but it's actually hours.

ahh ok thanks

**Comment by aniel300** [comment]
this is happening again with the latest stable release

**Comment by aniel300** [comment]
this is happening again with the latest stable release

**Comment by SenexCrenshaw** [comment]
Check the latest image please

**Comment by aniel300** [comment]
i believe it was fixed, thanks
