### ISSUE TITLE
[Feature Request] auto add channel numbers based on how the channels are sorted in the imported playlist

### ISSUE THREAD

**Issue by mLgz0rn** [SenexCrenshaw/StreamMaster#7]
I also posted this in the suggestions channel on discord.

Would it be possible to auto add channel numbers based on how the channels are sorted in the imported playlist, like xteve does? i'm using m3u4u for m3u playlist and epg, and if a channel dosnt has a channel number it will just get imported with channel number 0.

If not, how about a way to sort the playlist streams by the playlist file channel order? then I can use the auto set channel numbers, and they still remain in the correct order.

Kind Regards.

**Comment by SenexCrenshaw** [comment]
How about this?
1. Import the m3u file and set a starting channel # for it. 
2. Each line it will either use the existing tvg_chno in the file or the starting # + whatever is the next one (starting # + 1)

For sorting the streams have a unique id as they are imported into the DB. I could expose that as the order of input for sorting. 

This should cover both scenarios.

LMK your thoughts

**Comment by SenexCrenshaw** [comment]
For the first scenario I could make "Channel 3" either the first starting # in the m3u file setup or +1 of the last channel # defined which in this case was 2 so +1 would be 3. 

I am thinking SM should scan for all channel #s first in the M3U and fill in the gaps from there. if none exist then just use the starting # as the base.

"For sorting, if they get a unique id ....." this is true. The ID is incremented from the first line to the last so I could just add this in the UI as well. "Import order"

**Comment by jimmymarbles** [comment]
Would it be possible to import scan the channels in the m3u, list the contents, allow you to specify a starting channel number then have a start checkbox and a stop checkbox to complete the import?

In my case, I have an m3u file with a lot of entries, I only want a portion and would prefer not to import all and then delete.

**Comment by SenexCrenshaw** [comment]
> Would it be possible to import scan the channels in the m3u, list the contents, allow you to specify a starting channel number then have a start checkbox and a stop checkbox to complete the import?
> 
> In my case, I have an m3u file with a lot of entries, I only want a portion and would prefer not to import all and then delete.

I had something similar in an earlier build but found the existing m3u editor did the same thing in as many clicks so modifying before or after the import didnt seem to help. I still need to import everything so I can mark them as hidden and this helps with tracking on subsequent refreshes of the file. If you want to continue this piece, please make a new feature request.

**Comment by jimmymarbles** [comment]
I am not the sharpest knife in the drawer and was unable to figure out how to tell SM to show me the stream list of the recently scanned m3u file.  All I see is SM successfully scanned the file and lists number of streams, but not an option to show imported entries so I can create the channels and assign the number.  
 
 If this function currently exists, then I can adapt.  
 
 Dull knife, OUT!

> > Would it be possible to import scan the channels in the m3u, list the contents, allow you to specify a starting channel number then have a start checkbox and a stop checkbox to complete the import?
> > In my case, I have an m3u file with a lot of entries, I only want a portion and would prefer not to import all and then delete.
> 
> I had something similar in an earlier build but found the existing m3u editor did the same thing in as many clicks so modifying before or after the import didnt seem to help. I still need to import everything so I can mark them as hidden and this helps with tracking on subsequent refreshes of the file. If you want to continue this piece, please make a new feature request.

**Comment by vicerak** [comment]
Hey, I tried to install and for some reason, it gets stuck on loading. What am I doing wrong?

**Comment by SenexCrenshaw** [comment]
i need to document everything!
Hit me up on discord and i can help debug on whats going on.

https://discord.gg/RXkz9KbU

**Comment by SenexCrenshaw** [comment]
> I am not the sharpest knife in the drawer and was unable to figure out how to tell SM to show me the stream list of the recently scanned m3u file. All I see is SM successfully scanned the file and lists number of streams, but not an option to show imported entries so I can create the channels and assign the number.
> 
> If this function currently exists, then I can adapt.
> 
> Dull knife, OUT!
> 
> > > Would it be possible to import scan the channels in the m3u, list the contents, allow you to specify a starting channel number then have a start checkbox and a stop checkbox to complete the import?
> > > In my case, I have an m3u file with a lot of entries, I only want a portion and would prefer not to import all and then delete.
> > 
> > 
> > I had something similar in an earlier build but found the existing m3u editor did the same thing in as many clicks so modifying before or after the import didnt seem to help. I still need to import everything so I can mark them as hidden and this helps with tracking on subsequent refreshes of the file. If you want to continue this piece, please make a new feature request.

Its fixed in v0.1.1. Just use the latest

**Comment by mLgz0rn** [comment]
So I just tested the latest version, and something funky seems to be up.

The ID's added does not match up with the channel number, which in theory they should when using a fresh DB
![fadfasd](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/1b963e61-b915-481a-b0cc-510070f923ce)

This makes the channels be out of order. 
Also no channel numbers are being added to the ones who has none.

![as123d](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/46566b35-7766-46d6-ba2a-00c0c26a5dfb)

**Comment by SenexCrenshaw** [comment]
Check out image
senexcrenshaw/streammaster:0.1.5-0012

It has both  in it. Unfortunately you have to delete and readd in your m3u file to pick up the new starting channel #.

> So I just tested the latest version, and something funky seems to be up.
> 
> The ID's added does not match up with the channel number, which in theory they should when using a fresh DB ![fadfasd](https://user-images.githubusercontent.com/6141439/242708113-1b963e61-b915-481a-b0cc-510070f923ce.png)
> 
> This makes the channels be out of order. Also no channel numbers are being added to the ones who has none.
> 
> ![as123d](https://user-images.githubusercontent.com/6141439/242708551-46566b35-7766-46d6-ba2a-00c0c26a5dfb.png)

Wrong image to test with. I have a new one coming.

**Comment by SenexCrenshaw** [comment]
Please try
senexcrenshaw/streammaster:0.1.5-0016

**Comment by mLgz0rn** [comment]
So I just tested with 0.1.7.
And the id and ch number does seem to match now.

However, I have no idea how it's getting the order it is, it does not follow the playlist order at all :D

![qawsdasda](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/9c256735-2135-44d4-8170-0c7cae2e8809)
![asdasdasrf](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/b86f3c4f-fbee-4a83-a860-6671ffefdeac)
![edaewfasf](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/b5529023-b17b-416e-885b-6672abe97fec)

**Comment by aniel300** [comment]
@SenexCrenshaw is there a way to make all channels either 0 or -1?

**Comment by SenexCrenshaw** [comment]
> So I just tested with 0.1.7.
> And the id and ch number does seem to match now.
> 
> However, I have no idea how it's getting the order it is, it does not follow the playlist order at all :D
> 
> ![qawsdasda](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/9c256735-2135-44d4-8170-0c7cae2e8809)
> ![asdasdasrf](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/b86f3c4f-fbee-4a83-a860-6671ffefdeac)
> ![edaewfasf](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/b5529023-b17b-416e-885b-6672abe97fec)
> 

Ah! I know why. It's multi threading. I'll fix that.

**Comment by SenexCrenshaw** [comment]
> @SenexCrenshaw is there a way to make all channels either 0 or -1?

No bulk. Make a feature request. I think bulk changing groups too!

**Comment by mLgz0rn** [comment]
> > So I just tested with 0.1.7.
> > And the id and ch number does seem to match now.
> > However, I have no idea how it's getting the order it is, it does not follow the playlist order at all :D
> > ![qawsdasda](https://user-images.githubusercontent.com/6141439/243123716-9c256735-2135-44d4-8170-0c7cae2e8809.png)
> > ![asdasdasrf](https://user-images.githubusercontent.com/6141439/243123720-b86f3c4f-fbee-4a83-a860-6671ffefdeac.png)
> > ![edaewfasf](https://user-images.githubusercontent.com/6141439/243123726-b5529023-b17b-416e-885b-6672abe97fec.png)
> 
> Ah! I know why. It's multi threading. I'll fix that.

Getting closer :D 
For some reason channels from 2 groups are getting the same channel numbers

![erqweq3213 (Phone)](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/d1758e64-70e9-4661-9e3b-b934e79e2d48)
![324123123 (Phone)](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/39197d2b-a33c-4217-94b6-45a2c248236c)

**Comment by SenexCrenshaw** [comment]
These are streams from different m3u files? I have it auto numbering just to each m3ufile.  LMK and we can discuss some work arounds if so.

**Comment by mLgz0rn** [comment]
> These are streams from different m3u files? I have it auto numbering just to each m3ufile. LMK and we can discuss some work arounds if so.

No this is from the same file.
It has 6 groups within it.

**Comment by SenexCrenshaw** [comment]
hmmm... i dont see this behavior. Have you tried with a fresh DB?

**Comment by mLgz0rn** [comment]
> hmmm... i dont see this behavior. Have you tried with a fresh DB?
Yeah, I do that every time I update the docker container since it won't start without doing it

**Comment by mLgz0rn** [comment]
Okay so I think I know what's wrong.

Are you not replacing the existing channel numbers?
Because the first group, I have added channel numbers to pretty much all of them in the file, from the second group onwards the channels has no numbers in the file, so SM starts adding channel numbers from first channel in the second group which then starts at 1 hence why it's getting duplicated channel numbers.

I think this is why I wanted you to replace existing channel numbers in the file.
Because my provider loves to add new channels and remove others so they end up with no number.

**Comment by SenexCrenshaw** [comment]
OK. I'll add a checkbox in to overwrite.

**Comment by SenexCrenshaw** [comment]
overWrite M3U Channels is in settings now in the latest build. lmk how it works for you

**Comment by mLgz0rn** [comment]
> overWrite M3U Channels is in settings now in the latest build. lmk how it works for you

Alright thanks, testing now!

**Comment by mLgz0rn** [comment]
Okay, just tested.

enabling the option does not seem to change anything, channel numbers does not override

**Comment by SenexCrenshaw** [comment]
It will overwrite now. If new streams are inserted into the file it will change the order btw on refreshes/reloads. If you make manual changes to the ch # in SM, those wont be overwritten.

**Comment by mLgz0rn** [comment]
> It will overwrite now. If new streams are inserted into the file it will change the order btw on refreshes/reloads. If you make manual changes to the ch # in SM, those wont be overwritten.

Seems to be working now!

**Comment by SenexCrenshaw** [comment]
excellent
