### ISSUE TITLE
Bug: Video Player not working in Brave Browser

### ISSUE THREAD

**Issue by jimmymarbles** [SenexCrenshaw/StreamMaster#70]
**Describe the Bug**
Video Player does not populate available streams in Brave Browser.
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/6432197/5a97f888-a821-4a7b-9ed0-3819a139cb05)

**Stream Master Info**
- Version Number: StreamMaster-0.2.13

**Link to logs (required)**

- Upload any relevant logs here [Gist](http://gist.github.com). _Do not upload attachments_.

![image](https://github.com/SenexCrenshaw/StreamMaster/assets/6432197/c0c0f84b-9577-4016-966f-72299fb9efd7)

**Comment by SenexCrenshaw** [comment]
The video player needs some work for sure. its not at the top of the list though.... 

#39 is another issue thats needs addressing

**Comment by aniel300** [comment]
i also experience this on chrome although i dont use this feature as much yet (idk fully how to use)

**Comment by SenexCrenshaw** [comment]
The video player is disabled for now. not sure if it will ever come back

**Comment by jimmymarbles** [comment]
Doh!  I was hoping the player would return.  It be nice so I could preview streams.

**Comment by aniel300** [comment]
> The video player is disabled for now. not sure if it will ever come back

can u add a ui option not only to see the provider url but also sm streaming url?
