### ISSUE TITLE
Bug: unable to delete group

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#71]
**Describe the Bug**
unable to delete group

**Stream Master Info**
latest stable available
 
**Link to logs (required)**
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/4f95f72f-2b59-487a-8f08-1decb50afe68)

**Comment by SenexCrenshaw** [comment]
You can only delete user created groups, not from the M3U files. Hide it if you dont want to see it
