### ISSUE TITLE
Bug: ghost groups even after deleting playlist file the file section 

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#72]
**Describe the Bug**
ghost groups even after deleting playlist file the file section. also can u add an option to delete groups as needed and desired by the end user even if those groups are part of playlist currently in the file section. 

**Stream Master Info**
- latest available stable

**Link to logs (required)**
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/b34225ec-6229-4bff-8960-6df3181879ae)

**Comment by SenexCrenshaw** [comment]
This is with the latest image? I dont know how you ended up with duplicate groups.. 

In SM. Go to settings -> Swagger (at bottom)
Click Channel Groups -> Get -> Try It Out -> Execute
<img width="1072" alt="image" src="https://github.com/SenexCrenshaw/StreamMaster/assets/35600301/3d08f685-e322-4e21-9d49-8945595274f0">

or 
http://(IP):7095/api/channelgroups

Send me the output please.

**Comment by aniel300** [comment]
[
  {
    "id": 432,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | 7/24 ÇCCUK",
    "rank": 53,
    "regexMatch": ""
  },
  {
    "id": 450,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | 7/24 ÇCCUK",
    "rank": 71,
    "regexMatch": ""
  },
  {
    "id": 493,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | 7/24 ÇCCUK",
    "rank": 90,
    "regexMatch": ""
  },
  {
    "id": 521,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | 7/24 ÇCCUK",
    "rank": 118,
    "regexMatch": ""
  },
  {
    "id": 525,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | 7/24 ÇCCUK",
    "rank": 122,
    "regexMatch": ""
  },
  {
    "id": 433,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | MÜZİK",
    "rank": 54,
    "regexMatch": ""
  },
  {
    "id": 452,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | MÜZİK",
    "rank": 73,
    "regexMatch": ""
  },
  {
    "id": 495,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | MÜZİK",
    "rank": 92,
    "regexMatch": ""
  },
  {
    "id": 522,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | MÜZİK",
    "rank": 119,
    "regexMatch": ""
  },
  {
    "id": 526,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | MÜZİK",
    "rank": 123,
    "regexMatch": ""
  },
  {
    "id": 430,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | YEŞİLÇAM SİNEMA",
    "rank": 51,
    "regexMatch": ""
  },
  {
    "id": 446,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | YEŞİLÇAM SİNEMA",
    "rank": 67,
    "regexMatch": ""
  },
  {
    "id": 489,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | YEŞİLÇAM SİNEMA",
    "rank": 86,
    "regexMatch": ""
  },
  {
    "id": 519,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | YEŞİLÇAM SİNEMA",
    "rank": 116,
    "regexMatch": ""
  },
  {
    "id": 523,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | YEŞİLÇAM SİNEMA",
    "rank": 120,
    "regexMatch": ""
  },
  {
    "id": 431,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | ÇOCUK",
    "rank": 52,
    "regexMatch": ""
  },
  {
    "id": 449,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | ÇOCUK",
    "rank": 70,
    "regexMatch": ""
  },
  {
    "id": 492,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | ÇOCUK",
    "rank": 89,
    "regexMatch": ""
  },
  {
    "id": 520,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | ÇOCUK",
    "rank": 117,
    "regexMatch": ""
  },
  {
    "id": 524,
    "isHidden": false,
    "isReadOnly": true,
    "name": "TR | ÇOCUK",
    "rank": 121,
    "regexMatch": ""
  }
]

**Comment by JHeat** [comment]
I was having the same issue. This appears to be UI related? After a full refresh the groups are gone. I found this out while troubleshooting my channels losing mapping.

NOTE: Thanks to the dev for creating this. I've needed something that effectively handles backup channels for quite some time.

**Comment by aniel300** [comment]
> I was having the same issue. This appears to be UI related? After a full refresh the groups are gone. I found this out while troubleshooting my channels losing mapping.
> 
> NOTE: Thanks to the dev for creating this. I've needed something that effectively handles backup channels for quite some time.

have u try the latest test image?
