### ISSUE TITLE
Bug: sm still updates playlist even though it is uncheck on the webui (i have my needs for this at the time being)

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#73]
**Describe the Bug**
sm still updates playlist even though it is uncheck on the webui (i have my needs for this at the time being)

**Stream Master Info**
latest stable available 

**Link to logs (required)**

**Comment by SenexCrenshaw** [comment]
Are you sure its auto-updating? I couldnt see in the code where that would happen. It can modify the playlist in the DB on a restart of the app though. Just wondering what changes were made so i can dig deeper.

**Comment by aniel300** [comment]
yes the reason i bump into this is because i manually changed the url on few channels and then after few days it would resset back to the original url.

**Comment by aniel300** [comment]
wont/ cant confirm at the moment. assuming it was fixed with latest pr therefore am closing this.
