### ISSUE TITLE
Feature Request: Choose between MPEG-TS(.ts)/HLS(.m3u8) if provider supports it

### ISSUE THREAD

**Issue by mLgz0rn** [SenexCrenshaw/StreamMaster#77]
**Describe the solution you'd like**
When adding a new m3u file, having the option to choose between .ts and .m3u8 for that file could be great.
Some providers supports this, and I think for most it's just as simple as changing the url to either .ts or .m3u8.
Maybe add a third option like (use m3u output), so if you are unsure if your provider supports either .ts or .m3u8 it will use whatever is being used in the m3u file.

**Additional context**

![output_type2](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/94281553-66d4-4107-ba6a-12ca6759a7fc)
![stream_output](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/ca127137-e136-4839-aece-e0ca286e30bc)

**Comment by SenexCrenshaw** [comment]
sounds good
