### ISSUE TITLE
Feature Request: option to disabled "channel-number=" from being in the m3u output link

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#8]
**Is your feature request related to a problem? Please describe.**
even though all channels have a channel number of "0" in the webui, they all get numbered starting from 1 in the m3u output link which result on my emby not matching the channels using "tvg-id" is there a way to turn of this?

**Describe the solution you'd like**
a way to turn of channel-number= from being in the m3u output link

**Describe alternatives you've considered**
n/a at this moment

**Additional context**
i can send screenshot or video if needed

thank you in advance.

**Comment by SenexCrenshaw** [comment]
Just remove ``channel-number=`` but keep ``tvg-chno=`` ?

EPGs are matched using ``tvg-id`` . Are you setting an EPG in for each channel in SM or you dont use one?

**Comment by aniel300** [comment]
at this moment am not using epg/ any external epg and am letting emby do that part also i meant to say "tvg-id" not "tvg-chno=". in addition how can i "Just remove channel-number=" from sm m3u output link "http://xxx:7095/api/streamgroups/0/m3u"?

**Comment by SenexCrenshaw** [comment]
I can put it in the next nightly for you to test with. So you just want to try removing ``channel-number`` and not also ``tvg_chno`` ?

Did you want  ``channel-number,tvg_chno`` to be the tvg_id ??

**Comment by aniel300** [comment]
because i use channels number in the tvg-id from https://www.tvchannellists.com to let emby do it things using is built in epg sources. in other words because the way am doing things channel-number is not helping me in this situation. if u think or know a better way to do this, please do let me know otherwise yes i need some options or way to disabled it although now that u mention "channel-number" and "tvg_chno" am not sure anymore what is causing my issue/ behavior i believe it is "channel-number" but am not sure any more. 

this is all that shows in sm m3u link, please give an option to include or not include them or advise what to do next. and yes if u can include it in the next nightly i will appreciate it, thanks. 

channel-id="4" channel-number="4" tvg-name="UP TV" tvg-chno="4" tvg-ID="uptv.us"

**Comment by SenexCrenshaw** [comment]
Ill  pop a new link in for you to test with. one what wont have those 2 fields.

**Comment by aniel300** [comment]
ok perfect and thank you.

**Comment by aniel300** [comment]
“Did you want  channel-number,tvg_chno to be the tvg_id ??” yes i think this can also work

**Comment by SenexCrenshaw** [comment]
wait. is it channel-id that is messing with you? I will create you some tests

**Comment by SenexCrenshaw** [comment]
Try image:
senexcrenshaw/streammaster:0.1.4-0001

**Comment by SenexCrenshaw** [comment]
if that doesnt work i think it might be the CUID being changed from the original. Ill address that now

**Comment by SenexCrenshaw** [comment]
senexcrenshaw/streammaster:0.1.4-0004

**Comment by aniel300** [comment]
> if that doesnt work i think it might be the CUID being changed from the original. Ill address that now

i think this was the issue and did the trick. do let me know once u merge it into the latest tag. i do also have few other issues/ behaviors not related to this that i will report later on. other than that thank you for time and support, keep up the good work.

**Comment by SenexCrenshaw** [comment]
Im going to release 0.1.4 with the fix.

**Comment by SenexCrenshaw** [comment]
the latest is online with this fix. you dont need the "2" link.

I will keep senexcrenshaw/streammaster:0.1.4-0004 around for a bit

**Comment by aniel300** [comment]
i take it back. the CUID fix didnt fix it for me once i enable the entire list/ channels back. the original playlist dosent include few things, however using the m3u2 did fix it at that point.

here are some more info/examples: 
original playlist: #EXTINF:0 CUID="13249" tvg-name="CBS" tvg-id="11.1" group-title=".Fort Myers-Naples, FL",CBS
sm playlist: #EXTINF:0 CUID="40729" channel-id="40729" channel-number="0" tvg-name="VICE" tvg-chno="0" tvg-ID="vice.us" tvg-logo="http://xxx:7095/api/files/5/https%3a%2f%2flogo.iptveditor.com%2fvice.png" group-title=".no locals (directv national channels)",VICE

so idk if it it channel-id and/or channel-number or something else but when channel-id/ channel-number aren't included then it works.

**Comment by SenexCrenshaw** [comment]
hmm. ok. ill keep this open for now. m3u2 is working for you though?

**Comment by aniel300** [comment]
yes it is

**Comment by aniel300** [comment]
i have a new issie. if i use the .m3u2 then not all groups get synced.

**Comment by SenexCrenshaw** [comment]
can you show me an example?

**Comment by aniel300** [comment]
is there a way to make channel-id, channel-number, tvg-chno etc adapt/get info from tvg-id? btw here is the example.
![tptAD0LPjU](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/ad0a87a1-147e-4604-9c25-42865449c1f5)
![0XCHihOhD8](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/a0036064-bb64-455d-ad08-456baf1a2806)

**Comment by SenexCrenshaw** [comment]
> i have a new issie. if i use the .m3u2 then not all groups get synced.

yes

**Comment by aniel300** [comment]
> > i have a new issie. if i use the .m3u2 then not all groups get synced.
> 
> yes

what do u mean "yes"?

**Comment by aniel300** [comment]
> group-title=".Fort Myers-Naples, FL",CBS

m3u: #EXTINF:0 CUID="13249" channel-id="13249" channel-number="322" tvg-name="CBS" tvg-chno="322" tvg-ID="11.1" tvg-logo="http://xxx:7095/images/default.png" group-title=".Fort Myers-Naples, FL",CBS

m3u2: #EXTINF:0 CUID="13249" tvg-name="CBS" tvg-ID="11.1" tvg-logo="http://xxx:7095/images/default.png" group-title=".Fort Myers-Naples, FL",CBS

**Comment by SenexCrenshaw** [comment]
The file from your provider has ``channel-id="13249" channel-number="322"`` in it?

Can you show me the line from SM with the regular m3u output. These look pretty close...

**Comment by aniel300** [comment]
> The file from your provider has `channel-id="13249" channel-number="322"` in it? 
> 
> Can you show me the line from SM with the regular m3u output. These look pretty close... 
1) this is coming from iptveditor, not sure if that answer ur question
2) i did
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/ecf2091a-c325-438c-87b0-176f2d29f569)

**Comment by SenexCrenshaw** [comment]
not the m3u2 output. the regular m3u output

**Comment by aniel300** [comment]
i did
![chrome_F84JJcBxJk](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/0bb08baf-10d3-443f-a00b-62452bb1eca7)

**Comment by SenexCrenshaw** [comment]
Ok. can you send me now the SM output with the m3u URL and not the m3u2 one.

**Comment by aniel300** [comment]
i did sent it all along, but here is again: 

#EXTINF:0 CUID="13249" channel-id="13249" channel-number="322" tvg-name="CBS" tvg-chno="322" tvg-ID="11.1" tvg-logo="http://xxx:7095/images/default.png" group-title=".Fort Myers-Naples, FL",CBS

**Comment by SenexCrenshaw** [comment]
i mean. the only thing left is to remove the icons. Does the iptveditor output work great in emby/plex?

**Comment by aniel300** [comment]
yes it does. but what do u mean remove the icons? am still having the original issue

**Comment by aniel300** [comment]
will it be possible to have like the one from iptveditor or have channel-number, etc (all the extra info that is on sm) mirror what is on tvg-ID?

**Comment by SenexCrenshaw** [comment]
Ill change m3u2 to match 
#EXTINF:0 CUID="13249" tvg-name="CBS" tvg-id="11.1" group-title=".Fort Myers-Naples, FL",CBS

Sound right?

**Comment by aniel300** [comment]
yes let's give that a try since, when we took off  channel-number and channel-id not all groups where synching so something broke

**Comment by aniel300** [comment]
@SenexCrenshaw isnt this what we are after? https://github.com/SenexCrenshaw/StreamMaster/issues/7#issuecomment-1572677816

**Comment by SenexCrenshaw** [comment]
try 
senexcrenshaw/streammaster:0.1.6-0002

**Comment by SenexCrenshaw** [comment]
> @SenexCrenshaw isn't this what we are after? #7

dont think so. that is auto channel numbering

**Comment by aniel300** [comment]
> > @SenexCrenshaw isn't this what we are after? #7
> 
> dont think so. that is auto channel numbering

ok

**Comment by aniel300** [comment]
> try senexcrenshaw/streammaster:0.1.6-0002

ok let me give this a try. m3u or m3u2?

**Comment by SenexCrenshaw** [comment]
2 please

**Comment by aniel300** [comment]
same situation only this 4 groups sync not only that but icons are missing i think which to expect since we are missing cache logos from sm. i think the next thing to do here is to make sure tvg-ID info also appears on  channel-number, etc while using the main "m3u" link because for some reason m3u2 is not synching all the groups.
![chrome_Blrgl2C6Cx](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/869f5485-500e-47dc-87a0-326eca320673)

**Comment by aniel300** [comment]
or maybe giving this a try? https://github.com/SenexCrenshaw/StreamMaster/issues/7

**Comment by aniel300** [comment]
@SenexCrenshaw have u beenn able to take a look at this?

**Comment by SenexCrenshaw** [comment]
Not sure where we left this. m3u2 matches what you asked for I believe. Anything else??

**Comment by aniel300** [comment]
it still broken for me and at this point there is two things we can try. 
1) make sure channel-number and tvg-chno get their info/ mirror the info from tvg-id have it be output on m3u and m3u2
and/or
2) mirror iptveditor format ag: "#EXTINF:0 CUID="13249" tvg-name="CBS" tvg-id="11.1" group-title=".Fort Myers-Naples, FL",CBS" but have it output on m3u and not m3u2 since that seems to be broken.

thank u in advance.

**Comment by aniel300** [comment]
@SenexCrenshaw any news on this?

**Comment by SenexCrenshaw** [comment]
> it still broken for me and at this point i think there is two things we can try.
> 
> 1. make sure channel-number and tvg-chno get their info/ mirror the info from tvg-id and have it be output on m3u and/or m3u2
> 
> and/or
> 
> 2. mirror iptveditor format ag: "#EXTINF:0 CUID="13249" tvg-name="CBS" tvg-id="11.1" group-title=".Fort Myers-Naples, FL",CBS" but have it output on m3u and not m3u2 since that seems to be broken.
> 
> thank u in advance.

Have you looked at m3u2?? It is the same format as #2

**Comment by aniel300** [comment]
> > it still broken for me and at this point i think there is two things we can try.
> > 
> > 1. make sure channel-number and tvg-chno get their info/ mirror the info from tvg-id and have it be output on m3u and/or m3u2
> > 
> > and/or
> > 
> > 2. mirror iptveditor format ag: "#EXTINF:0 CUID="13249" tvg-name="CBS" tvg-id="11.1" group-title=".Fort Myers-Naples, FL",CBS" but have it output on m3u and not m3u2 since that seems to be broken.
> > 
> > thank u in advance.
> 
> Have you looked at m3u2?? It is the same format as #2

idk how to answer this question

**Comment by SenexCrenshaw** [comment]
m3u2 mirrors iptveditor format ag: "#EXTINF:0 CUID="13249" tvg-name="CBS" tvg-id="11.1" group-title=".Fort Myers-Naples, FL",CBS" but have it output on m3u and not m3u2 since that seems to be broken.

**Comment by aniel300** [comment]
> m3u2 mirrors iptveditor format ag: "#EXTINF:0 CUID="13249" tvg-name="CBS" tvg-id="11.1" group-title=".Fort Myers-Naples, FL",CBS" but have it output on m3u and not m3u2 since that seems to be broken.

didi u just made this change? how can i test this?

**Comment by aniel300** [comment]
@SenexCrenshaw ?

**Comment by SenexCrenshaw** [comment]
No idea where we left this. If the current epg doesnt work for you please tell me what the output should look like for your issue. I almost feel like we should start a new thread....

**Comment by aniel300** [comment]
yes a new thread is fine and btw this is not related to ms epg features/ capabilities.
