### ISSUE TITLE
Feature Request: EPG Time offset (SM overwrites offset from providers)

### ISSUE THREAD

**Issue by mLgz0rn** [SenexCrenshaw/StreamMaster#80]
**Is your feature request related to a problem? Please describe.**

As it is right now, you are defaulting all programs/channels to +0000, which overwrites changes made in the imported epg from the providers, so if a program is set to +0200 in the provider epg, it will be set to +0000 by SM, which makes the data show up wrong.

**Describe the solution you'd like**

Allow us to set a epg time offset for each channel in the playlist streams.

should default to 00:00 or what ever is set in the imported EPG but be able to set to + or -.
Let's say EPG data for a channel is 2 hours off, I would then be able to use +02:00 or -02:00 to make the EPG data match

**Additional context**
Could be a clock button next to the other buttons
![aasda2 copy](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/ce979511-29c0-44b5-ac99-5308323d0d89)

**Comment by SenexCrenshaw** [comment]
will go into the next release
