### ISSUE TITLE
Bug: Live, New stripped EPG (XML)

### ISSUE THREAD

**Issue by infosecmatters2021** [SenexCrenshaw/StreamMaster#81]
Bug #47 wasn't resolved. 

Here's a copy of the EPG file. 

https://github.com/SenexCrenshaw/StreamMaster/files/11931988/epg.xml.zip

**Comment by SenexCrenshaw** [comment]
check it now with the latest release

**Comment by infosecmatters2021** [comment]
I updated my docker container this morning from the nightly version. They are still stripped.

**Comment by infosecmatters2021** [comment]
Hi,

I updated to the latest Docker release. Premiere works. Live and New are in the original file (see EasyEPG-XML.txt) but are stripped in the StreamMaster file. 
[EasyEPG-XML.txt](https://github.com/SenexCrenshaw/StreamMaster/files/13533540/EasyEPG-XML.txt)
[StreamMaster-epg.xml.txt](https://github.com/SenexCrenshaw/StreamMaster/files/13533541/StreamMaster-epg.xml.txt)

**Comment by infosecmatters2021** [comment]
@SenexCrenshaw Have you had a chance to look at the files I provided to see why New and Live are being stripped from the StreamMaster EPG file?
