### ISSUE TITLE
Bug: Slash (/) in stream name breaks streams URL

### ISSUE THREAD

**Issue by pmcnano** [SenexCrenshaw/StreamMaster#84]
**Describe the Bug**
Naming a stream with a slash (example: `24/7`) breaks the stream URL.

**Stream Master Info**
`0.2.18.0`

**Link to logs (required)**
No relevant logs, there's just a 404 but nothing in the logs, but here's the result stream url:
`http://192.168.0.220:7095/api/videostreams/stream/QQGGRzUuSWnanfCpQqhJwS94klYnXwyKDR5qLZYv3fU6dX7cGh1FGr8fEu52lc44hx6JaYWI9aVMEcIx8aMLGTdc-dHlgtgwJ2OnzxmWq3fKRtDY4fi_4VNiCW5Uho7E/24/7_Law_and_Order_SVU`

Obviously the issue is the `24/7` as it isn't encoded correctly.

**Comment by aniel300** [comment]
are u running the latest beta/ test image?

**Comment by pmcnano** [comment]
Lastest stable version.

**Comment by aniel300** [comment]
try using "ui-redui-0.2.18-ui-redui.1-0125" or the latest from https://hub.docker.com/r/senexcrenshaw/streammaster/tags and report back

**Comment by pmcnano** [comment]
It's weird, it...partially works? Using VLC...

- If I open the m3u and copy the stream URL, it works.....
- If I open the M3U, then the stream does not work?

**Comment by aniel300** [comment]
i will check this on my end by tomorrow

**Comment by aniel300** [comment]
> It's weird, it...partially works? Using VLC...
> 
> * If I open the m3u and copy the stream URL, it works.....
> * If I open the M3U, then the stream does not work?

i can confirm am not having this issue on my end, at least not with version ui-redui-0.2.18-ui-redui.1-0125

**Comment by mLgz0rn** [comment]
It's fixed btw

**Comment by SenexCrenshaw** [comment]
fixed in latest
