### ISSUE TITLE
Feature Request: Synchronize A/V Between Clients on LAN

### ISSUE THREAD

**Issue by JHeat** [SenexCrenshaw/StreamMaster#86]
With how efficient the SM Buffer is (~2s faster over VLC)

A delay or some other logic could be used to ensure all streams are synced on the LAN. This is nice when folks are over with streams going to multiple TV's.

**Comment by SenexCrenshaw** [comment]
its the buffer size that does this. when a client connects it gets the oldest data first and streams from that point. If you want them at the same point try decreasing your buffer to something very low. Right now the smallest is 1MB. I can change that. If this is something folks really want I could add a check box in settings to have clients start at the newest data. this would essentially negate buffering though.
