### ISSUE TITLE
Bug: EPG select is buggy

### ISSUE THREAD

**Issue by mLgz0rn** [SenexCrenshaw/StreamMaster#90]
**Describe the Bug**
When manually selecting an epg for a channel, the search box completely messes up.
Start typing in it, and at some point it will start deleting everything you type, and no results are coming up

![unknown_2023 09 21-15 19_1](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/c5b371bd-c99a-4798-a495-d9b95f39f43a)

**Stream Master Info**
- 0.2.18-19

**Comment by Austin1** [comment]
Can confirm, same issue
