### ISSUE TITLE
Feature Request: ability to add "backup" streams on the fly

### ISSUE THREAD

**Issue by aniel300** [SenexCrenshaw/StreamMaster#92]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
ability to add "backup" streams on the fly. 

**Describe alternatives you've considered**
n/a

**Additional context**
for my understating for me to be able to add back stream the channels need to be present on sm ui/db is it possible to add back up stream on the fly within the backup stream configuration section. on the fly backup stream dont need to be added to the playlist/ groups at that point

**Comment by SenexCrenshaw** [comment]
you have to create a custom stream first

**Comment by SenexCrenshaw** [comment]
investigating

**Comment by aniel300** [comment]
> investigating

keep me posted if this cant be implemented then creating the extra/ backup stream first wont be the end of the world
