### ISSUE TITLE
Bug: M3U Import Silently Fails If Duplicate Channel Exists

### ISSUE THREAD

**Issue by JHeat** [SenexCrenshaw/StreamMaster#93]
**Describe the Bug**
Importing an M3U that contains the same channel (including name, url etc.), results in a silent failure, where import shows successful but the resulting log shows a Critical error, including "wonky" output in the UI.

**Stream Master Info**
- Latest

**Link to logs (required)**
https://gist.github.com/JHeat/9a4611c8db334f9a5f0f5c93b1470ccb

**Comment by aniel300** [comment]
this might be why sm is not updating my channels url but idk for sure

**Comment by SenexCrenshaw** [comment]
Check with the latest and reopen if need be.
