### ISSUE TITLE
Bug: EPG <date> being removed from Guide Data

### ISSUE THREAD

**Issue by JHeat** [SenexCrenshaw/StreamMaster#94]
**Describe the Bug**
EPG <date> being removed from guide data. This provides the necessary info for Movie (<year>)

**Stream Master Info**
- Latest Docker 2.18.0

**Link to logs (required)**
- [Upload any relevant logs here] (https://gist.github.com/JHeat/be7272c84fa4da93ec6b5c0e5e9dfef9)

**Comment by SenexCrenshaw** [comment]
try the latest and lmk if it is still happening. if so i need to see a good and a bad epg entry

**Comment by SenexCrenshaw** [comment]
i def need to see an example of your epg that has this.
