### ISSUE TITLE
Feature Request: Show IP Address of each stream

### ISSUE THREAD

**Issue by R0ltec** [SenexCrenshaw/StreamMaster#97]
Good afternoon,

After finally getting your App to work, it looks to have some amazing potential and feature upgrade capabilities. While I next look to contribute to your outstanding work, I noticed that the IP address of the device streaming content isn’t anywhere to be found. Definitely a security issue as you never know who is watching once enough friends and family start streaming stuff from different places. You kind of know who is who based on IP , ISP and location. I wonder if instead of just IP, it could do a dns lookup and show the FQDN instead. Would be great!

**Comment by R0ltec** [comment]
If the FQDN (dns resolution) could also be shown, that would be amazing. Thanks for the great and quick work.

**Comment by aniel300** [comment]
> If the FQDN (dns resolution) could also be shown, that would be amazing. Thanks for the great and quick work.

maybe make another request so this new request doesn't get forgotten
